(function(){
  'use strict';

  const SUPABASE_URL='https://qnspmqsrbjcgrgpqkzgl.supabase.co';
  const SUPABASE_ANON_KEY='sb_publishable_pVjv5t2S338SsCW98VvwpA_PcpXBL7V';
  const AUTH_STORAGE_KEY='js-plan-auth-v1';
  const CURRENT_STUDENT_STORAGE_KEY='js-plan-current-student-v1';
  const LOCAL_DRAFT_KEY='js-plan-early-batch-draft-v1';
  const ACTIVE_PROFILE_ROLES=new Set(['admin','consultant','planner','viewer','manager','sales','assistant','reviewer','finance','observer']);
  const GUIDE=window.EARLY_BATCH_GUIDE_DATA||{};
  const RULES=window.EARLY_BATCH_RULES_2026||{};
  const GROUP_DATA=window.EARLY_BATCH_GROUPS_2026||{meta:{},groups:[]};
  const GROUPS=Array.isArray(GROUP_DATA.groups)?GROUP_DATA.groups:[];
  const QUALIFICATION_PROGRESS_STATUSES=new Set(['self_checked','preparing','submitted','passed']);
  const $=selector=>document.querySelector(selector);
  const $$=selector=>Array.from(document.querySelectorAll(selector));
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const clone=value=>JSON.parse(JSON.stringify(value));
  const nowISO=()=>new Date().toISOString();
  const unique=values=>[...new Set((values||[]).filter(value=>value!==null&&value!==undefined&&value!==''))];
  const hasValue=value=>value!==null&&value!==undefined&&String(value).trim()!=='';
  const owns=(object,key)=>Object.prototype.hasOwnProperty.call(object||{},key);

  const FALLBACK_CATEGORIES=[
    {id:'military',code:'01',title:'军事院校',summary:'年龄、婚姻、政治考核、体检、体测、面试与入学复查形成连续门槛。',groupIds:['military'],subcategories:['军校招生专业','政治考核','体质测试与面试','军检与入校复查'],qualification:'先核年龄、未婚、特控线与军检条件',admission:'资格链通过后再比较专业组计划和历史位次',career:'军队培养与分配，按培养目标和军种岗位执行',cost:'军籍、纪律、岗位地域与退出约束需提前接受'},
    {id:'police',code:'02',title:'公安政法院校',summary:'必须区分公安院校公安专业、司法行政警察类与普通专业，联考资格不能按校名推断。',groupIds:['police'],subcategories:['公安院校公安专业','中央司法警官学院','普通专业辨别'],qualification:'年龄、未婚、政审、身高视力、面试体测逐项核验',admission:'江苏类别内投档规则与兼报限制以当年文件为准',career:'公安联考或司法招警只覆盖明确具备资格的专业',cost:'体能、纪律与岗位选择仍有竞争，不承诺入警'},
    {id:'maritime',code:'03',title:'航海院校／专业',summary:'航海技术、轮机工程、船舶电子电气工程的视力、色觉与身高要求不同。',groupIds:['maritime'],subcategories:['航海技术','轮机工程','船舶电子电气工程'],qualification:'按具体专业核视力、色觉、复视、身高及体检方式',admission:'资格合格后比较院校专业组，不把海洋类专业混入',career:'职业指向船员和海上岗位，长期出海适应度重要',cost:'工作环境、证书培训和海上周期需纳入普通批比较'},
    {id:'local-special',code:'04',title:'地方专项',summary:'户籍、农村属性、连续户籍、连续学籍和实施区域缺一不可。',groupIds:['local-special'],subcategories:['实施区域','户籍与农村属性','三年学籍','资格公示'],qualification:'本人及监护人户籍、三年户籍学籍和特控线待核',admission:'必须匹配 2026 江苏实施区域与高校计划清单',career:'普通高校培养与自主就业，不等于定向分配',cost:'资格材料和公示节点必须提前完成'},
    {id:'rural-teacher',code:'05',title:'乡村教师定向',summary:'江苏乡村教师按本县报本县、签就业协议并连续服务 5 年，不能与部属公费师范混写。',groupIds:[],subcategories:['县区计划','定向协议','培养考核','五年服务'],qualification:'户籍县区必须有计划，并确认教师资格与招聘考核',admission:'按县区、专业和计划填报，录取后签署协议',career:'综合成绩排序选岗，材料称有编有岗仍待官方核验',cost:'服务地域、考研限制、违约责任须读协议原文'},
    {id:'medical',code:'06',title:'农村订单定向医学生',summary:'面向有计划县区生源，规培与基层服务相连；材料明确不是人人自动入编。',groupIds:['medical'],subcategories:['县区生源','定向协议','三年规培','六年服务'],qualification:'核户籍县区、应届要求、医学培养与履约接受度',admission:'逐县区、院校、专业组核招生计划和定岗信息',career:'乡镇卫生院或村卫生室，编制岗比例不能被保证',cost:'规培计入服务期，资格考试、违约与读研限制并存'},
    {id:'other',code:'07',title:'其他院校／特殊专业',summary:'外交、国关、北电科、消防、海关、飞行技术等各有独立条件，“其他”不等于无门槛。',groupIds:['other'],subcategories:['党政特色院校','马克思主义理论','小语种','飞行技术','核工程／军工定向','港校路径'],qualification:'先选具体学校专业，再读取其面试、政审、语种和身体条件',admission:'不同院校可能有第一志愿、前置报名或单独考核要求',career:'自主择业、国考择优、定向协议等终点完全不同',cost:'不承诺就业率、干部率、编制或固定分配'}
  ];

  const state={
    view:'dashboard',auth:{accessToken:'',refreshToken:'',user:null},students:[],currentStudent:null,record:null,
    cloudReady:true,cloudUpdatedAt:'',cloudRecord:null,localBaseCloudUpdatedAt:null,localBaseKnown:true,localDirty:false,needsSync:false,syncConflict:null,conflictExported:false,localDraftReady:true,recordWritable:false,recordLoadError:'',saveTimer:null,savePromise:null,toastTimer:null,loadingStudent:false,
    mapCategory:'military',matrix:{q:'',subject:'',category:'',gender:'',elective:'',selectedOnly:false,page:1,pageSize:25}
  };

  function defaultRecord(){return{
    schemaVersion:1,status:'准备中',
    profile:{subjectType:'',electives:[],gender:'',birthDate:'',maritalStatus:'',graduateType:'',score:'',rank:'',specialControlLine:'',hukouCounty:'',ruralHukou:'',guardianRuralHukou:'',hukouYears:'',schoolYears:'',actualAttendance:'',englishLanguage:'',oralExam:'',politicalIdentity:'',ordinaryBaseline:'',serviceAcceptance:'',careerPreference:'',notes:''},
    physical:{height:'',weight:'',nakedVisionLeft:'',nakedVisionRight:'',correctedVision:'',colorVision:'',laserSurgeryDate:'',hearing:'',physicalExam:'',otherNotes:''},
    qualificationChecks:{},mapChoices:{category:'military'},selectedGroupKeys:[],tasks:{},sourceChecks:{},agreements:{},notes:'',updatedAt:''
  }}
  function normalizeRecord(raw){
    const base=defaultRecord(),input=raw&&typeof raw==='object'?raw:{};
    return {...base,...input,profile:{...base.profile,...(input.profile||{}),electives:unique(input.profile?.electives||[])},physical:{...base.physical,...(input.physical||{})},qualificationChecks:{...(input.qualificationChecks||{})},mapChoices:{...base.mapChoices,...(input.mapChoices||{})},selectedGroupKeys:unique(input.selectedGroupKeys||input.selected_group_keys||[]),tasks:{...(input.tasks||{})},sourceChecks:{...(input.sourceChecks||{})},agreements:{...(input.agreements||{})}};
  }
  function storageJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch(err){return fallback}}
  function saveAuth(){try{localStorage.setItem(AUTH_STORAGE_KEY,JSON.stringify(state.auth))}catch(err){}}
  function clearAuth(){clearTimeout(state.saveTimer);state.saveTimer=null;state.savePromise=null;state.auth={accessToken:'',refreshToken:'',user:null};state.students=[];state.currentStudent=null;state.record=null;state.recordWritable=false;state.cloudReady=false;state.cloudUpdatedAt='';state.cloudRecord=null;state.localBaseCloudUpdatedAt=null;state.localBaseKnown=true;state.localDirty=false;state.needsSync=false;state.syncConflict=null;state.conflictExported=false;state.localDraftReady=true;try{localStorage.removeItem(AUTH_STORAGE_KEY)}catch(err){}}
  function currentStudentStorageKey(){return state.auth.user?.id?`${CURRENT_STUDENT_STORAGE_KEY}:${state.auth.user.id}`:CURRENT_STUDENT_STORAGE_KEY}
  function localDraftKey(studentId=state.currentStudent?.id){return `${LOCAL_DRAFT_KEY}:${state.auth.user?.id||'guest'}:${studentId||'none'}:2026`}
  function normalizeCloudVersion(value){return typeof value==='string'&&value?value:null}
  function readLocalDraft(raw){
    if(!raw||typeof raw!=='object')return null;
    if(raw.storageSchemaVersion===2&&raw.record&&typeof raw.record==='object'){
      const sync=raw.sync&&typeof raw.sync==='object'?raw.sync:{};const baseKnown=sync.baseKnown===true;
      return{record:normalizeRecord(raw.record),sync:{baseKnown,baseCloudUpdatedAt:baseKnown?normalizeCloudVersion(sync.baseCloudUpdatedAt):null,dirty:sync.dirty===true,savedAt:String(sync.savedAt||'')},raw,legacy:false};
    }
    return{record:normalizeRecord(raw),sync:{baseKnown:false,baseCloudUpdatedAt:null,dirty:true,savedAt:String(raw.updatedAt||'')},raw,legacy:true};
  }
  function saveLocalDraft(studentId=state.currentStudent?.id,record=state.record,options={}){
    if(!studentId||!record)return false;
    const touch=options.touch!==false,updatedAt=touch?nowISO():(record.updatedAt||nowISO());
    const dirty=owns(options,'dirty')?Boolean(options.dirty):(touch?true:state.localDirty);
    const baseKnown=owns(options,'baseKnown')?Boolean(options.baseKnown):state.localBaseKnown;
    const baseCloudUpdatedAt=baseKnown?normalizeCloudVersion(owns(options,'baseCloudUpdatedAt')?options.baseCloudUpdatedAt:state.localBaseCloudUpdatedAt):null;
    const draft={...record,updatedAt};const envelope={storageSchemaVersion:2,record:draft,sync:{baseCloudUpdatedAt,baseKnown,dirty,savedAt:nowISO()}};let saved=false;
    try{localStorage.setItem(localDraftKey(studentId),JSON.stringify(envelope));saved=true}catch(err){saved=false}
    state.localDraftReady=saved;
    if(studentId===state.currentStudent?.id){if(record===state.record)state.record.updatedAt=updatedAt;state.localDirty=dirty;state.localBaseKnown=baseKnown;state.localBaseCloudUpdatedAt=baseCloudUpdatedAt}
    return saved;
  }
  function conflictBackupKey(studentId=state.currentStudent?.id){return`${localDraftKey(studentId)}:conflict:${nowISO().replace(/[:.]/g,'-')}`}
  function listConflictBackups(studentId=state.currentStudent?.id){const prefix=`${localDraftKey(studentId)}:conflict:`,items=[];try{for(let index=0;index<localStorage.length;index+=1){const key=localStorage.key(index);if(!key?.startsWith(prefix))continue;const raw=localStorage.getItem(key);if(!raw)continue;try{items.push({key,savedAt:key.slice(prefix.length),draft:JSON.parse(raw)})}catch(err){items.push({key,savedAt:key.slice(prefix.length),raw})}}}catch(err){return[]}return items.sort((left,right)=>right.key.localeCompare(left.key))}
  function downloadJSON(value,filename){try{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=filename.replace(/[\\/:*?"<>|\s]+/g,'-');document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0);return true}catch(err){toast('导出失败，请不要刷新或关闭页面。');return false}}
  function downloadCurrentConflict(){if(!state.syncConflict)return;if(downloadJSON({format:'jiangsu-plan-early-batch-conflict-v1',exportedAt:nowISO(),studentId:state.currentStudent?.id||'',studentName:state.currentStudent?.name||'',draft:state.syncConflict.localRaw??state.syncConflict.localRecord},`提前批冲突草稿-${state.currentStudent?.name||'学生'}-${nowISO().slice(0,10)}.json`)){state.conflictExported=true;render();setSaveState('error','同步冲突');toast('当前本机冲突草稿已导出。')}}
  function downloadStoredConflicts(){const backups=listConflictBackups();if(!backups.length){toast('当前学生没有本机冲突备份。');return}downloadJSON({format:'jiangsu-plan-early-batch-conflict-backups-v1',exportedAt:nowISO(),studentId:state.currentStudent?.id||'',studentName:state.currentStudent?.name||'',backups},`提前批冲突备份-${state.currentStudent?.name||'学生'}-${nowISO().slice(0,10)}.json`)}
  function saveCurrentStudent(student){state.currentStudent=student||null;try{student?localStorage.setItem(currentStudentStorageKey(),JSON.stringify(student)):localStorage.removeItem(currentStudentStorageKey())}catch(err){}}
  function hasUnsafeMemoryConflict(){return Boolean(state.localDirty&&!state.localDraftReady&&!state.conflictExported)}
  function blockUnsafeConflictExit(){if(!hasUnsafeMemoryConflict())return false;toast('最新修改只在当前页面内存中，请先导出当前本机草稿。');return true}
  function decodeJwt(token){try{const part=String(token||'').split('.')[1];if(!part)return null;const base=part.replace(/-/g,'+').replace(/_/g,'/');const json=atob(base.padEnd(base.length+(4-base.length%4)%4,'='));return JSON.parse(decodeURIComponent(Array.from(json).map(c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join('')))}catch(err){return null}}
  function tokenExpiresSoon(){const payload=decodeJwt(state.auth.accessToken);return!payload?.exp||payload.exp*1000-Date.now()<120000}
  async function refreshSession(force=false){
    if(!state.auth.accessToken){const err=new Error('请先登录。');err.authExpired=true;throw err}
    if(!force&&!tokenExpiresSoon())return;
    if(!state.auth.refreshToken){const err=new Error('登录状态已过期，请重新登录。');err.authExpired=true;throw err}
    const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.auth.refreshToken})});
    if(!response.ok){const err=new Error('登录状态已过期，请重新登录。');err.authExpired=true;err.status=response.status;throw err}
    const data=await response.json();state.auth={accessToken:data.access_token||'',refreshToken:data.refresh_token||state.auth.refreshToken,user:data.user||state.auth.user};saveAuth();
  }
  async function apiFetch(path,options={}){
    await refreshSession(false);
    const request=()=>fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${state.auth.accessToken}`,'Content-Type':'application/json',...(options.headers||{})}});
    let response=await request();if(response.status===401){await refreshSession(true);response=await request()}
    if(!response.ok){const text=await response.text();const err=new Error(text||`请求失败（${response.status}）`);err.status=response.status;err.body=text;if(response.status===401)err.authExpired=true;throw err}
    if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null;
  }
  function showAuthCover(show){$('#authCover').hidden=!show;$('#appShell').hidden=show}
  function returnToLogin(message=''){if(blockUnsafeConflictExit())return false;clearAuth();showAuthCover(true);const frame=$('#authFrame');if(frame)frame.src=`../login_landing.html?next=early-batch%2F${message?`&notice=${encodeURIComponent(message)}`:''}`;return true}
  async function ensureProfile(user){
    const rows=await apiFetch(`profiles?select=role,status&id=eq.${encodeURIComponent(user.id)}&limit=1`);const profile=rows?.[0];
    if(profile){if(profile.status!=='active'||!ACTIVE_PROFILE_ROLES.has(profile.role))throw new Error('账号资料未启用，请联系管理员检查角色和状态。');return}
    await apiFetch('profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({id:user.id,email:user.email||'',display_name:user.user_metadata?.display_name||user.email||'',role:'viewer',status:'active'})});
    const created=await apiFetch(`profiles?select=role,status&id=eq.${encodeURIComponent(user.id)}&limit=1`);if(!created?.[0]||created[0].status!=='active'||!ACTIVE_PROFILE_ROLES.has(created[0].role))throw new Error('账号资料创建失败，请联系管理员。');
  }
  async function authenticateFromLanding(message){
    const action=message.action||'login';
    if(action==='reset-password'){const response=await fetch(`${SUPABASE_URL}/auth/v1/recover?redirect_to=${encodeURIComponent(new URL('../login_landing.html#login',location.href).href)}`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:String(message.email||'')})});if(!response.ok)throw new Error(await response.text());return{message:'已发送密码重置邮件，请到邮箱继续操作。',stay:true}}
    const endpoint=action==='register'?'signup':'token?grant_type=password';const body=action==='register'?{email:String(message.email||''),password:String(message.password||''),data:{role:'viewer',display_name:String(message.email||'').split('@')[0]}}:{email:String(message.email||''),password:String(message.password||'')};
    const response=await fetch(`${SUPABASE_URL}/auth/v1/${endpoint}`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());const data=await response.json();if(!data.access_token||!data.user?.id)throw new Error(action==='register'?'注册已提交，但当前仍需要邮箱验证。':'登录响应不完整。');
    const previous=state.auth;state.auth={accessToken:data.access_token,refreshToken:data.refresh_token||'',user:data.user};try{await ensureProfile(data.user);saveAuth()}catch(err){state.auth=previous;try{localStorage.removeItem(AUTH_STORAGE_KEY)}catch(storageErr){}throw err}return{message:action==='register'?'注册成功，正在进入系统…':'登录成功，正在进入系统…'};
  }
  async function handleAuthMessage(event){const frame=$('#authFrame')?.contentWindow;if(event.origin!==location.origin||event.source!==frame||event.data?.source!=='auth-login')return;try{const result=await authenticateFromLanding(event.data);if(!result.stay){await loadWorkspaceData();showAuthCover(false)}frame?.postMessage({source:'jiangsu-plan-auth',status:'ok',message:result.message},event.origin)}catch(err){if(err.authExpired)clearAuth();frame?.postMessage({source:'jiangsu-plan-auth',status:'error',message:`${event.data.action==='register'?'注册':'登录'}失败：${humanError(err)}`},event.origin)}}
  function humanError(err){const text=String(err?.message||err||'未知错误');if(/Invalid login credentials/i.test(text))return'账号或密码错误。';if(/user_already_exists|already registered/i.test(text))return'该邮箱已经注册，请直接登录。';if(/changed by another user|concurrent update|40001/i.test(text))return'该学生的提前批档案已被其他账号更新，请重新读取后再保存。';if(/student_early_batch_records|save_student_early_batch|PGRST20[245]/i.test(text))return'提前批云端数据表尚未启用，当前仅保存本机草稿。';return text.length>180?text.slice(0,180)+'…':text}
  function isMissingSchema(err){const text=String(err?.body||err?.message||'');return err?.status===404||/PGRST20[245]|student_early_batch_records.*(?:does not exist|schema cache)|save_student_early_batch.*schema cache/i.test(text)}

  async function fetchStudents(){const fields='id,owner_id,name,stage,subject_type,subject_choices,second_subjects,score,rank,gaokao_score,gaokao_rank,estimated_score,estimated_rank,updated_at';const rows=await apiFetch(`students?select=${fields}&archived=eq.false&order=updated_at.desc`);state.students=(rows||[]).filter(student=>!['specialty','专科'].includes(String(student.stage||'')))}
  function findStoredStudent(){const stored=storageJSON(currentStudentStorageKey(),null);return stored?.id?state.students.find(student=>student.id===stored.id)||null:null}
  function studentValue(student,...keys){for(const key of keys){const value=student?.[key];if(hasValue(value))return value}return''}
  function normalizeSubject(value){const text=String(value||'').toLowerCase();return /history|历史/.test(text)?'历史类':/physics|物理/.test(text)?'物理类':''}
  function profileFromStudent(student){if(!student)return{};return{subjectType:normalizeSubject(student.subject_type),electives:unique(student.subject_choices||student.second_subjects||[]).map(String),score:studentValue(student,'gaokao_score','estimated_score','score'),rank:studentValue(student,'gaokao_rank','estimated_rank','rank')}}
  function syncConflict(kind,draft,tableRecord,cloudUpdatedAt,cloudKnown=true){return{kind,legacy:Boolean(draft?.legacy),localRecord:draft?.record||defaultRecord(),localRaw:draft?.raw||draft?.record||defaultRecord(),localBaseCloudUpdatedAt:draft?.sync?.baseCloudUpdatedAt??null,localBaseKnown:Boolean(draft?.sync?.baseKnown),cloudRecord:tableRecord||null,cloudUpdatedAt:cloudUpdatedAt||'',cloudKnown}}
  async function loadRecordData(student){
    const localRaw=storageJSON(localDraftKey(student.id),null),draft=readLocalDraft(localRaw);let tableRecord=null,cloudUpdatedAt='',cloudReady=true;
    try{const rows=await apiFetch(`student_early_batch_records?select=*&student_id=eq.${encodeURIComponent(student.id)}&limit=1`);const row=rows?.[0];cloudUpdatedAt=row?.updated_at||'';tableRecord=row?normalizeRecord({...row.payload,status:row.status||row.payload?.status,updatedAt:row.updated_at}):null}catch(err){if(err.authExpired||err.status===401)throw err;if(isMissingSchema(err))cloudReady=false;else if(draft)cloudReady=false;else throw err}
    if(!cloudReady){return{record:draft?.record||defaultRecord(),cloudReady:false,cloudUpdatedAt:'',cloudRecord:null,localBaseCloudUpdatedAt:draft?.sync?.baseCloudUpdatedAt??null,localBaseKnown:draft?draft.sync.baseKnown:true,localDirty:draft?draft.sync.dirty:false,needsSync:draft?draft.sync.dirty:false,syncConflict:null}}
    if(!draft){return{record:tableRecord||defaultRecord(),cloudReady:true,cloudUpdatedAt,cloudRecord:tableRecord,localBaseCloudUpdatedAt:tableRecord?cloudUpdatedAt:null,localBaseKnown:true,localDirty:false,needsSync:false,syncConflict:null}}
    if(draft.sync.dirty){
      const safeCreate=!tableRecord&&draft.sync.baseKnown&&draft.sync.baseCloudUpdatedAt===null;
      const safeUpdate=Boolean(tableRecord&&draft.sync.baseKnown&&draft.sync.baseCloudUpdatedAt===cloudUpdatedAt);
      if(safeCreate||safeUpdate)return{record:draft.record,cloudReady:true,cloudUpdatedAt,cloudRecord:tableRecord,localBaseCloudUpdatedAt:draft.sync.baseCloudUpdatedAt,localBaseKnown:true,localDirty:true,needsSync:true,syncConflict:null};
      const kind=draft.legacy?'legacy_draft':!tableRecord?'cloud_missing':'cloud_changed';
      return{record:draft.record,cloudReady:true,cloudUpdatedAt,cloudRecord:tableRecord,localBaseCloudUpdatedAt:draft.sync.baseCloudUpdatedAt,localBaseKnown:draft.sync.baseKnown,localDirty:true,needsSync:true,syncConflict:syncConflict(kind,draft,tableRecord,cloudUpdatedAt)};
    }
    if(!draft.sync.baseKnown||(!tableRecord&&draft.sync.baseCloudUpdatedAt!==null)){
      const kind=!draft.sync.baseKnown?'legacy_draft':'cloud_missing';
      return{record:draft.record,cloudReady:true,cloudUpdatedAt,cloudRecord:tableRecord,localBaseCloudUpdatedAt:draft.sync.baseCloudUpdatedAt,localBaseKnown:draft.sync.baseKnown,localDirty:false,needsSync:false,syncConflict:syncConflict(kind,draft,tableRecord,cloudUpdatedAt)};
    }
    return{record:tableRecord||draft.record,cloudReady:true,cloudUpdatedAt,cloudRecord:tableRecord,localBaseCloudUpdatedAt:tableRecord?cloudUpdatedAt:null,localBaseKnown:true,localDirty:false,needsSync:false,syncConflict:null};
  }
  function applyLoadedRecord(student,loaded){
    state.record=loaded.record;state.cloudReady=loaded.cloudReady;state.cloudUpdatedAt=loaded.cloudUpdatedAt||'';state.cloudRecord=loaded.cloudRecord||null;state.localBaseCloudUpdatedAt=loaded.localBaseCloudUpdatedAt??null;state.localBaseKnown=loaded.localBaseKnown!==false;state.localDirty=Boolean(loaded.localDirty);state.needsSync=Boolean(loaded.needsSync);state.syncConflict=loaded.syncConflict||null;state.conflictExported=false;state.recordWritable=!state.syncConflict;state.recordLoadError='';
    let importedChanged=false;
    if(!state.syncConflict){const imported=profileFromStudent(student);Object.entries(imported).forEach(([key,value])=>{if(key==='electives'){if(!state.record.profile.electives.length&&value.length){state.record.profile.electives=value;importedChanged=true}}else if(!hasValue(state.record.profile[key])&&hasValue(value)){state.record.profile[key]=value;importedChanged=true}})}
    if(importedChanged){state.localDirty=true;state.needsSync=true}
    state.mapCategory=state.record.mapChoices.category||'military';state.matrix.subject=state.record.profile.subjectType||'';state.matrix.page=1;
    if(!state.syncConflict)saveLocalDraft(student.id,state.record,{touch:importedChanged,dirty:state.localDirty,baseKnown:state.localBaseKnown,baseCloudUpdatedAt:state.localBaseCloudUpdatedAt});
  }
  async function loadWorkspaceData(){
    setSaveState('saving','正在读取');state.recordLoadError='';state.recordWritable=false;let fetchError=null;
    try{await fetchStudents()}catch(err){if(err.authExpired||err.status===401)throw err;fetchError=err;const cached=storageJSON(currentStudentStorageKey(),null);state.students=cached?.id?[cached]:[];if(!state.students.length){state.currentStudent=null;state.record=defaultRecord();state.recordLoadError=humanError(err);setSaveState('error','读取失败');render();return false}}
    const chosen=findStoredStudent()||state.students[0]||null;if(!chosen){saveCurrentStudent(null);state.record=defaultRecord();state.recordWritable=true;state.cloudUpdatedAt='';state.cloudRecord=null;state.localBaseCloudUpdatedAt=null;state.localBaseKnown=true;state.localDirty=false;state.needsSync=false;state.syncConflict=null;state.conflictExported=false;render();setSaveState('saved','云端已连接');return true}
    try{const loaded=await loadRecordData(chosen);if(fetchError){loaded.cloudReady=false;loaded.needsSync=false}saveCurrentStudent(chosen);applyLoadedRecord(chosen,loaded);render();if(state.syncConflict)setSaveState('error','同步冲突');else if(state.needsSync&&state.cloudReady){setSaveState('saving','正在同步本机草稿');await saveRecord('')}else setSaveState(state.cloudReady?'saved':'error',state.cloudReady?'云端已连接':state.localDraftReady?'本机草稿':'无法保存');if(fetchError)toast('网络暂不可用，已打开本机草稿。');return true}catch(err){if(err.authExpired||err.status===401)throw err;saveCurrentStudent(chosen);state.record=defaultRecord();state.cloudReady=false;state.cloudUpdatedAt='';state.cloudRecord=null;state.localBaseCloudUpdatedAt=null;state.localBaseKnown=true;state.localDirty=false;state.needsSync=false;state.syncConflict=null;state.conflictExported=false;state.recordWritable=false;state.recordLoadError=humanError(err);setSaveState('error','读取失败');render();toast('读取提前批档案失败：'+humanError(err));return false}
  }
  function setSaveState(kind,label){const el=$('#saveState');if(!el)return;el.dataset.state=kind;el.textContent=label}
  function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
  function isConcurrentConflict(err){return/changed by another user|concurrent update|40001/i.test(String(err?.body||err?.message||err||''))}
  function currentMemoryDraft(){const currentRecord=clone(state.record),sync={baseKnown:state.localBaseKnown,baseCloudUpdatedAt:state.localBaseCloudUpdatedAt,dirty:true,savedAt:nowISO()};return{record:currentRecord,raw:{storageSchemaVersion:2,record:currentRecord,sync},legacy:false,sync}}
  function enterMemoryOnlyDraft(studentId,message='本机草稿和云端均未保存，请先导出当前草稿。'){
    const draft=currentMemoryDraft();state.localDraftReady=false;state.localDirty=true;state.needsSync=true;state.recordWritable=false;state.syncConflict=syncConflict('memory_only',draft,null,state.cloudUpdatedAt,false);state.conflictExported=false;setSaveState('error','仅存页面内存');render();toast(message);
  }
  function enterRuntimeSyncConflict(studentId){
    const draft=currentMemoryDraft();
    saveLocalDraft(studentId,state.record,{touch:false,dirty:true,baseKnown:state.localBaseKnown,baseCloudUpdatedAt:state.localBaseCloudUpdatedAt});
    state.localDirty=true;state.needsSync=true;state.recordWritable=false;state.syncConflict=syncConflict('concurrent',draft,null,state.cloudUpdatedAt,false);state.conflictExported=false;setSaveState('error','同步冲突');render();toast('云端已有更新，本机草稿已保留；请重新读取后选择版本。');
  }
  function queueSave(message='修改已保存'){if(!state.currentStudent?.id||!state.recordWritable||state.syncConflict)return;const localSaved=saveLocalDraft(undefined,undefined,{dirty:true});state.localDirty=true;state.needsSync=true;if(!localSaved&&!state.cloudReady){enterMemoryOnlyDraft(state.currentStudent.id);return}setSaveState('saving',localSaved?'保存中':'正在保存云端');clearTimeout(state.saveTimer);if(!localSaved){state.saveTimer=null;saveRecord(message,{fromTimer:true});return}state.saveTimer=setTimeout(()=>{state.saveTimer=null;saveRecord(message,{fromTimer:true})},650)}
  async function flushPendingSave(){if(state.saveTimer){clearTimeout(state.saveTimer);state.saveTimer=null;await saveRecord('',{fromTimer:true})}else if(state.savePromise)await state.savePromise}
  async function saveRecord(message='修改已保存',options={}){
    if(!state.currentStudent?.id||!state.record||!state.recordWritable||state.syncConflict)return false;if(!options.fromTimer){clearTimeout(state.saveTimer);state.saveTimer=null}
    const studentId=state.currentStudent.id,localSaved=saveLocalDraft(studentId,state.record,{touch:!options.fromTimer,dirty:true});state.localDirty=true;state.needsSync=true;
    if(!state.cloudReady){if(!localSaved)enterMemoryOnlyDraft(studentId,'浏览器本机存储不可用，且云端表尚未启用；请先导出当前草稿。');else{setSaveState('error','本机草稿');if(message)toast('已保存到本机；管理员执行提前批数据库迁移后可同步云端。')}return false}
    const operation=async()=>{
      if(state.currentStudent?.id!==studentId||state.syncConflict)return false;
      const snapshot=clone(state.record);snapshot.schemaVersion=1;if(!snapshot.updatedAt){snapshot.updatedAt=nowISO();state.record.updatedAt=snapshot.updatedAt;saveLocalDraft(studentId,state.record,{touch:false,dirty:true})}
      if(!state.localBaseKnown){enterRuntimeSyncConflict(studentId);return false}
      const expectedVersion=state.localBaseCloudUpdatedAt;
      try{
        const saved=await apiFetch('rpc/save_student_early_batch',{method:'POST',body:JSON.stringify({p_student_id:studentId,p_status:snapshot.status||'准备中',p_payload:snapshot,p_expected_updated_at:expectedVersion})});const row=Array.isArray(saved)?saved[0]:saved;const savedVersion=row?.updated_at;
        if(!savedVersion)throw new Error('云端保存未返回版本号，已保留本机草稿。');
        if(state.currentStudent?.id===studentId){const changedAfterSnapshot=state.record.updatedAt!==snapshot.updatedAt;state.cloudUpdatedAt=savedVersion;state.cloudRecord=normalizeRecord({...snapshot,updatedAt:savedVersion});state.localBaseCloudUpdatedAt=savedVersion;state.localBaseKnown=true;state.localDirty=changedAfterSnapshot;state.needsSync=changedAfterSnapshot;saveLocalDraft(studentId,state.record,{touch:false,dirty:changedAfterSnapshot,baseKnown:true,baseCloudUpdatedAt:savedVersion});setSaveState(changedAfterSnapshot?'saving':'saved',changedAfterSnapshot?'还有修改待同步':'已保存');if(message&&!changedAfterSnapshot)toast(message)}
        return true;
      }catch(err){
        if(err.authExpired||err.status===401){if(!localSaved)enterMemoryOnlyDraft(studentId,'登录状态已过期，且本机草稿未能落盘；请先导出当前草稿。');returnToLogin('登录状态已过期');return false}
        if(isConcurrentConflict(err)){if(state.currentStudent?.id===studentId)enterRuntimeSyncConflict(studentId);return false}
        if(isMissingSchema(err))state.cloudReady=false;
        if(state.currentStudent?.id===studentId){if(!localSaved)enterMemoryOnlyDraft(studentId,`本机与云端均未保存：${humanError(err)}；请先导出当前草稿。`);else{state.localDirty=true;state.needsSync=true;setSaveState('error','待同步');toast(`云端未保存，修改已保留在本机：${humanError(err)}`)}}return false;
      }
    };
    state.savePromise=(state.savePromise||Promise.resolve()).catch(()=>false).then(operation);return state.savePromise;
  }

  function categories(){
    const supplied=Array.isArray(GUIDE.categories)?GUIDE.categories:Array.isArray(GUIDE.categoryTree)?GUIDE.categoryTree:Array.isArray(GUIDE.knowledgeTree)?GUIDE.knowledgeTree:[];
    if(!supplied.length)return FALLBACK_CATEGORIES;
    const aliases={police:'public-security-judicial',medical:'rural-medical'};
    return FALLBACK_CATEGORIES.map(base=>{const match=supplied.find(item=>item.id===base.id||item.id===aliases[base.id]||item.categoryId===base.id||item.title===base.title||item.label===base.title);return match?{...base,...match,id:base.id,title:match.title||match.label||match.name||base.title,subcategories:match.subcategories||match.children||base.subcategories}:base});
  }
  function categoryById(id){return categories().find(item=>item.id===id)||categories()[0]}
  function groupCountForCategory(category){if(!category.groupIds?.length)return null;return GROUPS.filter(group=>category.groupIds.includes(group.categoryId)).length}
  function selectedGroupCount(){return state.record?.selectedGroupKeys?.length||0}
  function scoreSummary(student=state.currentStudent){if(!student)return'尚未选择学生';const p=state.record?.profile||{};const subject=p.subjectType||normalizeSubject(student.subject_type)||'选科待补';const electives=unique(p.electives||[]);const score=p.score||studentValue(student,'gaokao_score','estimated_score','score');const rank=p.rank||studentValue(student,'gaokao_rank','estimated_rank','rank');return`${subject}${electives.length?'｜'+electives.join('+'):''}${score?`｜${score} 分`:''}${rank?`｜位次 ${rank}`:''}`}
  function ageAt(dateString,target='2026-09-01'){if(!dateString)return null;const birth=new Date(`${dateString}T00:00:00`),at=new Date(`${target}T00:00:00`);if(Number.isNaN(birth.getTime()))return null;let age=at.getFullYear()-birth.getFullYear();if(at.getMonth()<birth.getMonth()||(at.getMonth()===birth.getMonth()&&at.getDate()<birth.getDate()))age-=1;return age}
  function qualificationProgressCount(){return Object.values(state.record?.qualificationChecks||{}).filter(status=>QUALIFICATION_PROGRESS_STATUSES.has(status)).length}
  function readiness(){
    const p=state.record?.profile||{},physical=state.record?.physical||{};
    const profileKeys=['subjectType','gender','birthDate','maritalStatus','graduateType','score','rank','specialControlLine','hukouCounty','ruralHukou','guardianRuralHukou','hukouYears','schoolYears','actualAttendance','ordinaryBaseline','serviceAcceptance'];
    const physicalKeys=['height','nakedVisionLeft','nakedVisionRight','colorVision','physicalExam'];
    const profileDone=profileKeys.filter(key=>hasValue(p[key])).length+(p.electives?.length?1:0),physicalDone=physicalKeys.filter(key=>hasValue(physical[key])).length;
    const checkDone=qualificationProgressCount(),taskDone=Object.values(state.record?.tasks||{}).filter(value=>value==='done'||value==='not_applicable'||value===true).length;
    return Math.min(100,Math.round((profileDone+physicalDone+Math.min(checkDone,8)+Math.min(taskDone,8)+Math.min(selectedGroupCount(),3))/(profileKeys.length+1+physicalKeys.length+8+8+3)*100));
  }
  function updateStudentHeader(){const student=state.currentStudent;$('#studentName').textContent=student?.name||'请选择学生';$('#studentAvatar').textContent=student?.name?.slice(0,1)||'未';const progress=readiness();$('#cycleProgressBar').style.width=`${progress}%`;$('#cycleProgressText').textContent=`准备度 ${progress}%`}
  function pageHead(eyebrow,title,description,actions=''){return`<header class="page-head"><div><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${actions?`<div class="page-actions">${actions}</div>`:''}</header>`}
  function choiceHTML(name,value,label,current){return`<label class="choice"><input type="radio" name="${esc(name)}" value="${esc(value)}" ${String(current)===String(value)?'checked':''}><span>${esc(label)}</span></label>`}
  function statusOptions(current){return[['','请选择'],['not_started','未开始'],['self_checked','已自查'],['preparing','准备中'],['submitted','已提交'],['passed','已通过'],['failed','未通过'],['official_pending','等官方通知']].map(([value,label])=>`<option value="${value}" ${current===value?'selected':''}>${label}</option>`).join('')}
  function emptyStudentHTML(){return`${pageHead('EARLY ADMISSION 2026','先选择一个学生','资格画像、备选专业组和办理状态都按学生独立保存。')}<div class="empty-state"><strong>还没有可用的学生档案</strong><p>先在学生档案中建立学生，或确认当前账号拥有对应学生的查看权限。</p><a class="button primary" href="../students/index.html">去学生档案</a></div>`}
  function recordLoadErrorHTML(){return`${pageHead('EARLY ADMISSION 2026','提前批档案暂未安全打开','为避免用空白内容覆盖原记录，本页已暂停编辑。')}<div class="empty-state"><strong>读取失败，尚未写入任何内容</strong><p>${esc(state.recordLoadError||'请检查网络后重试。')}</p><button class="button primary" type="button" id="retryWorkspace">重新读取</button></div>`}
  function syncConflictHTML(){
    const conflict=state.syncConflict||{},reason=conflict.kind==='legacy_draft'?'这份旧版本机草稿没有记录它从哪个云端版本开始编辑。':conflict.kind==='cloud_missing'?'本机草稿记录的云端基线已经不存在。':conflict.kind==='concurrent'?'保存期间云端被其他账号更新。':conflict.kind==='memory_only'?'浏览器未能写入本机草稿，同时本次云端保存也没有完成。':'本机草稿的基线版本与当前云端版本不一致。';
    const base=conflict.localBaseKnown?(conflict.localBaseCloudUpdatedAt||'当时云端无记录'):'未知',cloud=conflict.cloudKnown?(conflict.cloudUpdatedAt||'当前云端无记录'):'尚未重新读取',canLeave=!hasUnsafeMemoryConflict();
    return`${pageHead('SYNC CONFLICT','检测到本机草稿与云端冲突','系统已停止自动覆盖并切换为只读状态；本机草稿内容保持不变。')}<div class="empty-state"><strong>需要先选择安全的继续方式</strong><p>${esc(reason)} 为避免覆盖其他规划师或学生的新修改，当前不会自动保存到云端。</p><div class="baseline-alert"><b>版本对照</b><p>本机草稿基线：${esc(base)}｜当前云端：${esc(cloud)}${state.localDraftReady?'':'｜本机存储不可用，请先导出草稿，且勿刷新或关闭页面'}</p></div>${conflict.cloudKnown?'<button class="button primary" type="button" id="useCloudVersion">保留本机备份并打开云端版本</button>':'<button class="button primary" type="button" id="retrySyncConflict">重新读取云端版本</button>'} <button class="button" type="button" id="downloadCurrentConflict">${state.conflictExported?'已导出当前草稿':'导出当前本机草稿'}</button>${canLeave?' <a class="button" href="../students/index.html">暂不处理</a>':''}</div>`;
  }
  function preserveConflictBackup(conflict){const key=conflictBackupKey();try{localStorage.setItem(key,JSON.stringify(conflict.localRaw??conflict.localRecord??defaultRecord()));return key}catch(err){return''}}
  function useCloudVersion(){
    const conflict=state.syncConflict;if(!conflict?.cloudKnown)return;
    if(!preserveConflictBackup(conflict)){toast('无法创建本机冲突备份，未切换版本；可先导出当前草稿。');return}
    const nextRecord=clone(conflict.cloudRecord||defaultRecord()),nextBase=conflict.cloudRecord?conflict.cloudUpdatedAt:null,nextEnvelope={storageSchemaVersion:2,record:{...nextRecord,updatedAt:nextRecord.updatedAt||nowISO()},sync:{baseCloudUpdatedAt:nextBase,baseKnown:true,dirty:false,savedAt:nowISO()}};
    try{localStorage.setItem(localDraftKey(state.currentStudent.id),JSON.stringify(nextEnvelope))}catch(err){state.localDraftReady=false;render();toast('云端版本尚未打开：活动草稿写入失败，原稿和冲突备份均已保留。');return}
    state.localDraftReady=true;state.record=nextEnvelope.record;state.cloudRecord=conflict.cloudRecord||null;state.cloudUpdatedAt=conflict.cloudUpdatedAt||'';state.localBaseCloudUpdatedAt=nextBase;state.localBaseKnown=true;state.localDirty=false;state.needsSync=false;state.syncConflict=null;state.conflictExported=false;state.recordWritable=true;state.mapCategory=state.record.mapChoices.category||'military';state.matrix.subject=state.record.profile.subjectType||'';render();setSaveState('saved',state.cloudRecord?'云端已连接':'新建草稿');toast('已打开云端版本；原本机草稿已保留为冲突备份，可在学生选择窗口导出。');
  }
  async function refreshSyncConflictCloud(){
    const conflict=state.syncConflict,studentId=state.currentStudent?.id;if(!conflict||!studentId)return;
    setSaveState('saving','正在读取云端');
    try{const rows=await apiFetch(`student_early_batch_records?select=*&student_id=eq.${encodeURIComponent(studentId)}&limit=1`);const row=rows?.[0],cloudUpdatedAt=row?.updated_at||'',cloudRecord=row?normalizeRecord({...row.payload,status:row.status||row.payload?.status,updatedAt:row.updated_at}):null;if(state.currentStudent?.id!==studentId)return;state.cloudReady=true;state.cloudUpdatedAt=cloudUpdatedAt;state.cloudRecord=cloudRecord;state.syncConflict={...conflict,cloudRecord,cloudUpdatedAt,cloudKnown:true};render();setSaveState('error','同步冲突')}catch(err){if(err.authExpired||err.status===401)returnToLogin('登录状态已过期');else{setSaveState('error','读取失败');toast('重新读取云端失败：'+humanError(err))}}
  }
  function render(){
    if(!state.record)state.record=defaultRecord();$$('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));
    if(state.recordLoadError){$('#appView').innerHTML=recordLoadErrorHTML();updateStudentHeader();bindView();return}
    if(!state.currentStudent){$('#appView').innerHTML=emptyStudentHTML();updateStudentHeader();return}
    if(state.syncConflict){$('#appView').innerHTML=syncConflictHTML();updateStudentHeader();bindView();return}
    const renderers={dashboard:renderDashboard,profile:renderProfile,map:renderMap,matrix:renderMatrix,physical:renderPhysical,precheck:renderPrecheck,agreement:renderAgreement,timeline:renderTimeline,career:renderCareer,sources:renderSources};
    $('#appView').innerHTML=(renderers[state.view]||renderDashboard)();updateStudentHeader();bindView();
  }
  function qualificationFor(categoryId){
    const p=state.record?.profile||{},f=state.record?.physical||{},missing=[],fails=[],pending=[];const age=ageAt(p.birthDate);const num=value=>hasValue(value)?Number(value):null;
    const need=(key,label,source=p)=>{if(!hasValue(source[key]))missing.push(label)};
    if(categoryId==='military'){
      ['birthDate','maritalStatus','specialControlLine'].forEach(key=>need(key,{birthDate:'出生日期',maritalStatus:'婚姻状态',specialControlLine:'特控线状态'}[key]));need('nakedVisionLeft','左眼裸眼视力',f);need('nakedVisionRight','右眼裸眼视力',f);
      if(age!==null&&(age<16||age>20))pending.push(`按2026-09-01暂估为${age}周岁，可能超出资料线索16—20周岁；正式年龄截止日待2026官方确认`);if(p.maritalStatus==='married')fails.push('资料线索要求未婚');if(p.specialControlLine==='no')fails.push('资料线索要求达到特殊类型招生控制线');if(f.laserSurgeryDate)pending.push('激光手术满半年需按军检正式标准核验');pending.push('政治考核、体测、心理检测、面试和军检结果只能以官方结论为准');
    }else if(categoryId==='police'){
      ['birthDate','gender','maritalStatus'].forEach(key=>need(key,{birthDate:'出生日期',gender:'性别',maritalStatus:'婚姻状态'}[key]));need('height','身高',f);need('nakedVisionLeft','左眼裸眼视力',f);need('nakedVisionRight','右眼裸眼视力',f);need('colorVision','色觉',f);
      if(age!==null&&(age<16||age>22))pending.push(`按2026-09-01暂估为${age}周岁，可能超出资料线索年龄范围；正式截止日待2026官方确认`);if(p.maritalStatus==='married')fails.push('资料线索要求未婚');const minHeight=p.gender==='female'?160:p.gender==='male'?170:null;if(minHeight&&num(f.height)!==null&&num(f.height)<minHeight)fails.push(`身高低于资料线索中的${minHeight}cm`);const bmi=num(f.height)>0&&num(f.weight)>0?num(f.weight)/((num(f.height)/100)**2):null;const bmiRange=p.gender==='female'?[17.1,25.7]:p.gender==='male'?[17.3,27.3]:null;if(bmi!==null&&bmiRange&&(bmi<bmiRange[0]||bmi>bmiRange[1]))pending.push(`BMI约${bmi.toFixed(1)}，超出公安专业资料线索${bmiRange[0]}—${bmiRange[1]}；司法路径及2026正式标准另核`);const leftVision=num(f.nakedVisionLeft),rightVision=num(f.nakedVisionRight);if(leftVision!==null&&leftVision<4.7)fails.push('左眼裸眼视力低于当前资料出现过的最低线4.7');else if(leftVision!==null&&leftVision<4.8)pending.push('左眼4.7—4.8处于公安4.8与中警院4.7/4.8冲突区间，需按具体专业官方标准核验');if(rightVision!==null&&rightVision<4.7)fails.push('右眼裸眼视力低于当前资料出现过的最低线4.7');else if(rightVision!==null&&rightVision<4.8)pending.push('右眼4.7—4.8处于公安4.8与中警院4.7/4.8冲突区间，需按具体专业官方标准核验');if(f.colorVision==='abnormal')fails.push('资料线索要求无色盲色弱');pending.push('体测项目、政审、面试及具体专业联考资格待2026官方核验');
    }else if(categoryId==='maritime'){
      ['height','nakedVisionLeft','nakedVisionRight','correctedVision','colorVision'].forEach(key=>need(key,{height:'身高',nakedVisionLeft:'左眼裸眼视力',nakedVisionRight:'右眼裸眼视力',correctedVision:'矫正视力',colorVision:'色觉'}[key],f));if(f.colorVision==='abnormal')fails.push('资料线索显示航海类通常不接受色盲色弱');pending.push('航海技术与轮机/船电标准不同，必须选定专业后逐校核验');
    }else if(categoryId==='local-special'){
      ['hukouCounty','ruralHukou','guardianRuralHukou','hukouYears','schoolYears','actualAttendance','specialControlLine'].forEach(key=>need(key,{hukouCounty:'户籍县区',ruralHukou:'本人农村属性',guardianRuralHukou:'父母一方/监护人农村户籍',hukouYears:'连续户籍年限',schoolYears:'连续学籍年限',actualAttendance:'实际连续就读',specialControlLine:'特控线状态'}[key]));if(p.ruralHukou==='no')fails.push('资料线索要求本人属于实施区域农村户籍');if(p.guardianRuralHukou==='no')fails.push('资料线索要求父母一方或法定监护人户籍在实施区域农村');if(num(p.hukouYears)!==null&&num(p.hukouYears)<3)fails.push('连续户籍不足3年');if(num(p.schoolYears)!==null&&num(p.schoolYears)<3)fails.push('连续学籍不足3年');if(p.actualAttendance==='no')fails.push('资料线索要求在户籍所在县高中实际连续就读');if(p.specialControlLine==='no')fails.push('资料线索要求达到特殊类型招生控制线');pending.push('实施区域和高校清单等待2026江苏官方发布');
    }else if(categoryId==='rural-teacher'){
      need('hukouCounty','户籍县区');need('serviceAcceptance','服务与协议接受度');if(p.serviceAcceptance==='no')fails.push('不接受定向服务和协议约束');pending.push('必须本县报本县，并以2026县区计划和就业协议为准');
    }else if(categoryId==='medical'){
      need('hukouCounty','户籍县区');need('graduateType','应往届');need('serviceAcceptance','服务与协议接受度');if(p.graduateType==='repeat')fails.push('资料线索要求应届高中毕业生');if(p.serviceAcceptance==='no')fails.push('不接受基层服务和协议约束');pending.push('县区计划、规培、岗位与编制比例等待2026官方文件及协议核验');
    }else{pending.push('“其他院校”条件差异很大，需选定学校和专业后逐项读取官方章程')}
    if(fails.length)return{state:'fail',label:'明显不符合',detail:fails.join('；'),missing,pending};if(missing.length)return{state:'missing',label:'缺少信息',detail:`还需填写：${missing.join('、')}`,missing,pending};return{state:'pending',label:'等待2026官方核验',detail:pending.join('；'),missing,pending};
  }

  function renderDashboard(){
    const progress=readiness(),selected=selectedGroupCount(),p=state.record.profile,check=qualificationFor(state.mapCategory);const focus=[];
    if(!p.ordinaryBaseline)focus.push({icon:'基',title:'先完成普通批底稿',detail:'写清不走提前批时可接受的学校、专业和城市，提前批才能做真正的加法。',view:'profile'});
    if(!p.gender||!p.birthDate||!p.subjectType)focus.push({icon:'像',title:'补全资格画像',detail:'性别、年龄、选科和户籍会直接改变可报通道。',view:'profile'});
    if(check.state==='missing')focus.push({icon:'检',title:`补齐${categoryById(state.mapCategory).title}判断信息`,detail:check.detail,view:state.mapCategory==='maritime'||state.mapCategory==='police'||state.mapCategory==='military'?'physical':'profile'});
    if(!selected)focus.push({icon:'组',title:'建立第一版专业组清单',detail:'从工作簿499组中筛选；其中高校专项、综评A为独立通道，不生成伪录取概率。',view:'matrix'});
    if(!qualificationProgressCount())focus.push({icon:'办',title:'推进前置办理清单',detail:'只保存“未开始/准备中/已提交”等状态，不采集亲属违法等高度敏感详情。',view:'precheck'});
    return`<section class="hero-panel"><div class="hero-copy"><span class="eyebrow">2026 江苏本科提前批</span><h1>${esc(state.currentStudent.name)}，先判“能不能报”，再判断“值不值得报”。</h1><p>${esc(scoreSummary())}。提前批正式录取后不再参加后续普通批录取，因此系统先建立普通批基线，再展开资格、专业组、协议代价与职业终点。</p><button class="button primary" type="button" data-go-view="map">展开提前批决策地图 →</button></div><div class="hero-aside"><div><span class="eyebrow">READINESS</span><h3>提前批准备度</h3><p>只反映信息和任务完成度，不代表资格结论或录取概率。</p></div><div class="readiness-ring" style="--progress:${progress}%"><div><strong>${progress}%</strong><small>准备度</small></div></div></div></section>
      <section class="metric-grid"><article class="metric-card"><span>工作簿专业组</span><strong>${GROUP_DATA.meta?.groupCount||GROUPS.length||499}</strong><small>含高校专项151组、综评A 23组独立通道</small></article><article class="metric-card"><span>我的备选</span><strong>${selected}</strong><small>按学生独立保存</small></article><article class="metric-card"><span>当前通道</span><strong>${esc(categoryById(state.mapCategory).code)}</strong><small>${esc(categoryById(state.mapCategory).title)}</small></article><article class="metric-card"><span>资格状态</span><strong>${check.state==='fail'?'×':check.state==='missing'?'…':'待核'}</strong><small>${esc(check.label)}</small></article></section>
      ${p.ordinaryBaseline?'':`<div class="baseline-alert"><b>先不要直接拿提前批分数表做推荐</b><p>普通批底稿还没有建立。提前批最危险的误区，是只看“能低分进名校”，却没比较专业、地域、服务协议和录取后失去普通批机会的代价。</p></div>`}
      <section class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h2>现在最该做什么</h2><p>资格优先，分数参考在后；不会输出“包录”“包分配”。</p></div></div><div class="focus-list">${focus.slice(0,5).map(item=>`<div class="focus-item"><span class="focus-icon">${esc(item.icon)}</span><div><b>${esc(item.title)}</b><p>${esc(item.detail)}</p></div><button class="button" type="button" data-go-view="${esc(item.view)}">去完成</button></div>`).join('')||'<div class="focus-item"><span class="focus-icon">核</span><div><b>进入来源复核</b><p>把当前候选逐校对照2026官方计划、招生章程和考核通知。</p></div><button class="button" data-go-view="sources">去复核</button></div>'}</div></div><div class="panel"><div class="panel-head"><div><h2>四步决策顺序</h2><p>每一步都可能淘汰不适合的通道。</p></div></div><div class="status-list">${[['1','普通批基线','不报提前批时我能接受什么'],['2','资格与前置','选科、性别、户籍、体检、政审、面试'],['3','专业组比较','同一行比较2026计划和2025参考'],['4','协议与终点','服务期、岗位竞争、退出代价']].map(row=>`<div class="status-row"><div><b>${row[0]}. ${row[1]}</b><p>${row[2]}</p></div><span class="badge ${row[0]==='1'&&p.ordinaryBaseline?'green':'orange'}">${row[0]==='1'&&p.ordinaryBaseline?'已建立':'继续核验'}</span></div>`).join('')}</div></div></section>`;
  }

  function renderProfile(){
    const p=state.record.profile,age=ageAt(p.birthDate);return`${pageHead('STUDENT PROFILE','提前批资格画像','这里保存资格判断所需的最小信息；政审亲属详情等高度敏感内容不在本系统采集。','<button class="button primary" type="button" id="saveNow">立即保存</button>')}
      <section class="profile-layout"><form id="profileForm" class="form-panel">
        <section class="form-section"><h2>一、选科与成绩底座</h2><p>分数和位次只用于历史参考；先确认选科满足专业组要求。</p><div class="form-grid"><label class="field"><span>首选科目</span><select data-field="profile.subjectType"><option value="">请选择</option><option value="物理类" ${p.subjectType==='物理类'?'selected':''}>物理类</option><option value="历史类" ${p.subjectType==='历史类'?'selected':''}>历史类</option></select></label><label class="field"><span>再选科目</span><input data-field="profile.electivesText" value="${esc((p.electives||[]).join('、'))}" placeholder="例如：化学、生物"></label><label class="field"><span>当前分数</span><input data-field="profile.score" inputmode="numeric" value="${esc(p.score)}" placeholder="例如 610"></label><label class="field"><span>当前位次</span><input data-field="profile.rank" inputmode="numeric" value="${esc(p.rank)}" placeholder="例如 28000"></label><div class="field wide"><span>是否达到特殊类型招生控制线</span><div class="choice-grid">${choiceHTML('specialControlLine','yes','达到',p.specialControlLine)}${choiceHTML('specialControlLine','no','未达到',p.specialControlLine)}${choiceHTML('specialControlLine','unknown','待出分/待核',p.specialControlLine)}</div></div></div></section>
        <section class="form-section"><h2>二、基础身份与前置资格</h2><p>不同通道的年龄、性别计划、应往届、口试和政治面貌要求不同。</p><div class="form-grid"><label class="field"><span>性别（用于招生计划匹配）</span><select data-field="profile.gender"><option value="">请选择</option><option value="male" ${p.gender==='male'?'selected':''}>男</option><option value="female" ${p.gender==='female'?'selected':''}>女</option></select></label><label class="field"><span>出生日期</span><input type="date" data-field="profile.birthDate" value="${esc(p.birthDate)}"><small class="field-hint">按2026-09-01估算：${age===null?'待填写':age+'周岁'}</small></label><label class="field"><span>婚姻状态</span><select data-field="profile.maritalStatus"><option value="">请选择</option><option value="unmarried" ${p.maritalStatus==='unmarried'?'selected':''}>未婚</option><option value="married" ${p.maritalStatus==='married'?'selected':''}>已婚</option></select></label><label class="field"><span>应往届</span><select data-field="profile.graduateType"><option value="">请选择</option><option value="fresh" ${p.graduateType==='fresh'?'selected':''}>应届</option><option value="repeat" ${p.graduateType==='repeat'?'selected':''}>往届</option></select></label><label class="field"><span>外语语种</span><input data-field="profile.englishLanguage" value="${esc(p.englishLanguage)}" placeholder="例如：英语"></label><label class="field"><span>外语口试</span><select data-field="profile.oralExam"><option value="">请选择</option><option value="passed" ${p.oralExam==='passed'?'selected':''}>已合格</option><option value="registered" ${p.oralExam==='registered'?'selected':''}>已报名</option><option value="none" ${p.oralExam==='none'?'selected':''}>未参加</option><option value="pending" ${p.oralExam==='pending'?'selected':''}>待通知</option></select></label><label class="field wide"><span>政治面貌（仅用于个别院校资格判断）</span><select data-field="profile.politicalIdentity"><option value="">请选择</option><option value="party" ${p.politicalIdentity==='party'?'selected':''}>中共党员（含预备）</option><option value="league" ${p.politicalIdentity==='league'?'selected':''}>共青团员</option><option value="other" ${p.politicalIdentity==='other'?'selected':''}>其他</option></select></label></div></section>
        <section class="form-section"><h2>三、户籍、学籍与定向接受度</h2><p>地方专项、乡村教师和定向医学生必须落到具体县区与连续年限。</p><div class="form-grid"><label class="field wide"><span>户籍县区</span><input data-field="profile.hukouCounty" value="${esc(p.hukouCounty)}" placeholder="例如：盐城市××县（区）"></label><label class="field"><span>本人农村户籍/农村属性</span><select data-field="profile.ruralHukou"><option value="">请选择</option><option value="yes" ${p.ruralHukou==='yes'?'selected':''}>是</option><option value="no" ${p.ruralHukou==='no'?'selected':''}>否</option><option value="unknown" ${p.ruralHukou==='unknown'?'selected':''}>待资格部门确认</option></select></label><label class="field"><span>父母一方/监护人农村户籍</span><select data-field="profile.guardianRuralHukou"><option value="">请选择</option><option value="yes" ${p.guardianRuralHukou==='yes'?'selected':''}>符合</option><option value="no" ${p.guardianRuralHukou==='no'?'selected':''}>不符合</option><option value="unknown" ${p.guardianRuralHukou==='unknown'?'selected':''}>待资格部门确认</option></select></label><label class="field"><span>当地连续户籍年限</span><input data-field="profile.hukouYears" inputmode="decimal" value="${esc(p.hukouYears)}" placeholder="年"></label><label class="field"><span>当地高中连续学籍年限</span><input data-field="profile.schoolYears" inputmode="decimal" value="${esc(p.schoolYears)}" placeholder="年"></label><label class="field"><span>是否在该校实际连续就读</span><select data-field="profile.actualAttendance"><option value="">请选择</option><option value="yes" ${p.actualAttendance==='yes'?'selected':''}>是</option><option value="no" ${p.actualAttendance==='no'?'selected':''}>否</option><option value="unknown" ${p.actualAttendance==='unknown'?'selected':''}>待核</option></select></label><label class="field"><span>是否接受定向服务协议</span><select data-field="profile.serviceAcceptance"><option value="">请选择</option><option value="yes" ${p.serviceAcceptance==='yes'?'selected':''}>接受</option><option value="uncertain" ${p.serviceAcceptance==='uncertain'?'selected':''}>需看协议</option><option value="no" ${p.serviceAcceptance==='no'?'selected':''}>不接受</option></select></label></div></section>
        <section class="form-section"><h2>四、普通批基线与职业边界</h2><p>提前批只有在去向真正优于普通批基线时才值得填。</p><div class="form-grid"><label class="field wide"><span>普通批可接受底稿</span><textarea data-field="profile.ordinaryBaseline" placeholder="例如：普通批可以接受南京及周边公办院校的计算机/电子信息，不接受偏远地区和长服务期协议。">${esc(p.ordinaryBaseline)}</textarea></label><label class="field wide"><span>职业方向与明确排除项</span><textarea data-field="profile.careerPreference" placeholder="写清军警、出海、基层服务、地域限制、考研等边界。">${esc(p.careerPreference)}</textarea></label><label class="field wide"><span>补充备注</span><textarea data-field="profile.notes" placeholder="只记录报考决策所需信息，不填写亲属政审敏感详情。">${esc(p.notes)}</textarea></label></div></section>
      </form><aside class="sticky-summary"><div class="summary-card"><span class="eyebrow">QUALIFICATION BASE</span><h2>当前画像摘要</h2><div class="summary-list"><div class="summary-row"><span>选科</span><b>${esc(p.subjectType||'待补')} ${esc((p.electives||[]).join('+'))}</b></div><div class="summary-row"><span>成绩</span><b>${esc(p.score||'—')} 分｜位次 ${esc(p.rank||'—')}</b></div><div class="summary-row"><span>年龄</span><b>${age===null?'待补':age+'周岁'}</b></div><div class="summary-row"><span>户籍</span><b>${esc(p.hukouCounty||'待补')}</b></div><div class="summary-row"><span>普通批基线</span><b>${p.ordinaryBaseline?'已建立':'未建立'}</b></div></div><p class="summary-note">画像完整不等于资格合格。系统内的二手资料只能帮助发现缺口，最终必须以2026江苏官方文件、院校章程和现场结论为准。</p></div></aside></section>`;
  }

  function renderMap(){
    const selected=categoryById(state.mapCategory),count=groupCountForCategory(selected),check=qualificationFor(selected.id);
    const lanes=[['资格门槛',selected.qualification],['前置办理',selected.id==='local-special'?'县区资格审核、公示与材料节点':selected.id==='other'?'按院校完成报名、口试、面试或政审':'按类别完成体检、政审、面试、体测或协议'],['专业组筛选',selected.admission],['录取判断','和普通批基线逐项比较；正式录取后不再参加后续普通批'],['职业与代价',`${selected.career}；${selected.cost}`]];
    return`${pageHead('DECISION MAP','提前批决策地图','点击七大类别，像思维导图一样向下展开资格、办理、专业组、录取与职业终点。','<button class="button" type="button" data-go-view="matrix">打开499组矩阵</button>')}
      <section class="map-shell"><div class="map-toolbar"><p>主树为江苏本科提前批七类；高校专项、综评A在矩阵中标为“独立批次位置”，不混入普通提前批推荐池。</p><span class="badge ${check.state==='fail'?'red':check.state==='missing'?'blue':'orange'}">${esc(check.label)}</span></div><div class="map-canvas"><div class="map-root"><button type="button" aria-label="江苏本科提前批七类"><b>江苏本科提前批</b><small>资格优先 · 普通批基线在前 · 2026官方规则待核</small></button></div><div class="category-branches">${categories().map(category=>{const n=groupCountForCategory(category);return`<button type="button" class="category-node ${category.id===selected.id?'active':''}" data-category-id="${esc(category.id)}"><span>${esc(category.code)}</span><b>${esc(category.title)}</b><small>${esc(category.summary)}</small><i>${n===null?'专项':n+'组'}</i></button>`}).join('')}</div><div class="map-detail"><div class="map-detail-head"><div><span class="eyebrow">${esc(selected.code)} / EXPANDED</span><h2>${esc(selected.title)}</h2><p>${esc(selected.summary)}</p></div><button class="button primary" type="button" data-map-to-matrix="${esc((selected.groupIds||[])[0]||'')}">${count===null?'查看办理条件':`查看${count}个专业组`} →</button></div><div class="result-banner" data-state="${esc(check.state)}"><span class="badge ${check.state==='fail'?'red':check.state==='missing'?'blue':'orange'}">${esc(check.label)}</span><div><strong>当前学生判断</strong><p>${esc(check.detail)}</p></div></div><div class="map-lanes">${lanes.map((lane,index)=>`<article class="lane"><span>0${index+1}</span><b>${esc(lane[0])}</b><p>${esc(lane[1])}</p></article>`).join('')}</div><div class="subnodes">${(selected.subcategories||[]).map(item=>`<button type="button" class="subnode" data-category-detail="${esc(selected.id)}">${esc(typeof item==='string'?item:item.title||item.label||item.name)}</button>`).join('')}</div></div></div></section>`;
  }

  function fitGroup(group){
    const p=state.record.profile,missing=[],fails=[];if(p.subjectType&&group.subjectType!==p.subjectType)fails.push('首选科目不符');
    if(group.gender==='男'&&p.gender==='female')fails.push('仅男生计划');if(group.gender==='女'&&p.gender==='male')fails.push('仅女生计划');if(!p.gender&&group.gender!=='不限')missing.push('性别');
    const electives=unique(p.electives||[]).map(String);const req=String(group.elective||'不限');if(req!=='不限'){
      const needed=req==='化和生'?['化学','生物']:[req];if(!electives.length)missing.push('再选科目');else if(needed.some(subject=>!electives.some(value=>value.includes(subject.replace('学','')))))fails.push(`需${req}`);
    }
    if(group.separateTrack)return{state:'separate',label:'独立批次位置'};if(fails.length)return{state:'fail',label:fails.join('、')};if(missing.length)return{state:'missing',label:`缺${missing.join('、')}`};return{state:'pending',label:'基础匹配，资格待核'};
  }
  function filteredGroups(){
    const f=state.matrix,q=f.q.trim().toLowerCase(),selected=new Set(state.record.selectedGroupKeys||[]);return GROUPS.filter(group=>{
      if(f.subject&&group.subjectType!==f.subject)return false;if(f.category&&group.categoryId!==f.category)return false;if(f.gender&&group.gender!==f.gender)return false;if(f.elective&&group.elective!==f.elective)return false;if(f.selectedOnly&&!selected.has(group.id))return false;
      if(q){const hay=[group.school,group.groupName,group.code,group.province,group.city,group.categoryRaw,...(group.majors||[]).map(major=>major.name)].join(' ').toLowerCase();if(!hay.includes(q))return false}return true;
    });
  }
  function deltaHTML(value,unit=''){if(value===null||value===undefined)return'<span class="delta">—</span>';const n=Number(value);return`<span class="delta">${n>0?'+':''}${n}${unit}</span>`}
  function renderMatrix(){
    const rows=filteredGroups(),pages=Math.max(1,Math.ceil(rows.length/state.matrix.pageSize));state.matrix.page=Math.min(state.matrix.page,pages);const start=(state.matrix.page-1)*state.matrix.pageSize,visible=rows.slice(start,start+state.matrix.pageSize),selected=new Set(state.record.selectedGroupKeys||[]);const electives=unique(GROUPS.map(group=>group.elective)).sort();
    return`${pageHead('499 GROUP MATRIX','2026 提前批相关专业组矩阵','工作簿共499组，其中高校专项151组、综评A 23组属于独立通道；2026组投档线与2025组内专业最低分不同口径，只展示中性参考差值。','<button class="button" type="button" id="toggleSelected">'+(state.matrix.selectedOnly?'查看全部':'只看我的备选')+'</button>')}
      <div class="baseline-alert"><b>先资格、后分数</b><p>军校、公安、定向等通道不使用普通批“冲稳保概率”。无资格或资格待核时，历史分数只显示为参考，不生成录取概率。</p></div>
      <div class="filter-bar"><input id="matrixQuery" value="${esc(state.matrix.q)}" placeholder="搜索学校、专业组代码或专业"><select id="matrixSubject"><option value="">全部选科</option><option value="物理类" ${state.matrix.subject==='物理类'?'selected':''}>物理类</option><option value="历史类" ${state.matrix.subject==='历史类'?'selected':''}>历史类</option></select><select id="matrixCategory"><option value="">全部类别</option>${[['military','军校'],['police','公安'],['maritime','航海'],['local-special','地方专项'],['university-special','高校专项（独立）'],['medical','医学定向'],['other','其他'],['comprehensive-a','综评A（独立）']].map(([v,l])=>`<option value="${v}" ${state.matrix.category===v?'selected':''}>${l}</option>`).join('')}</select><select id="matrixGender"><option value="">全部性别计划</option><option value="男" ${state.matrix.gender==='男'?'selected':''}>仅男</option><option value="女" ${state.matrix.gender==='女'?'selected':''}>仅女</option><option value="不限" ${state.matrix.gender==='不限'?'selected':''}>不限</option></select><select id="matrixElective"><option value="">全部再选科目</option>${electives.map(value=>`<option value="${esc(value)}" ${state.matrix.elective===value?'selected':''}>${esc(value)}</option>`).join('')}</select></div>
      <div class="filter-summary"><span>找到 <b>${rows.length}</b> 个专业组；第 ${state.matrix.page}/${pages} 页</span><span>跨口径参考差值＝2026组投档线－2025组内专业最低分，不代表涨跌</span></div>
      <div class="matrix-wrap"><table class="matrix-table"><thead><tr><th>备选</th><th>类别/资格</th><th>学校与专业组</th><th>选科/性别</th><th>2026计划</th><th>2026组投档</th><th>2025专业最低</th><th>跨口径参考差值</th><th>专业</th></tr></thead><tbody>${visible.map(group=>{const fit=fitGroup(group);const score2026Text=group.scoreRankStatus==='not_applicable_comprehensive_a'?'不适用':group.score2026??'缺失';return`<tr><td class="select-cell"><input type="checkbox" data-group-select="${esc(group.id)}" ${selected.has(group.id)?'checked':''} aria-label="选择${esc(group.groupName)}"></td><td><span class="badge ${fit.state==='fail'?'red':fit.state==='missing'?'blue':'orange'}">${esc(group.categoryRaw)}</span><small>${esc(fit.label)}</small><small>工作簿数据待2026官方复核</small></td><td><button class="school-button" type="button" data-group-detail="${esc(group.id)}">${esc(group.school)}</button><small>${esc(group.code)}｜${esc(group.groupName)}｜${esc(group.province)}${group.city?`·${esc(group.city)}`:''}</small></td><td>${esc(group.subjectType)}<small>${esc(group.elective)}｜${esc(group.gender)}</small></td><td><b>${esc(group.plan2026)}</b><small>2025计划 ${esc(group.plan2025)}</small></td><td><div class="score-pair"><span>${esc(score2026Text)}${typeof score2026Text==='number'?'分':''}</span><span>${group.rank2026?`位次${group.rank2026}`:group.scoreRankStatus==='not_applicable_comprehensive_a'?'另行核算':'位次缺失'}</span></div></td><td><div class="score-pair"><span>${group.score2025??'缺失'}${group.score2025?'分':''}</span><span>${group.rank2025?`位次${group.rank2025}`:'位次缺失'}</span></div></td><td>${deltaHTML(group.scoreDelta,'分')}<small>参考位次差 ${group.rankDelta===null||group.rankDelta===undefined?'—':`${group.rankDelta>0?'+':''}${group.rankDelta}`}</small><small>不同口径，不表示涨跌</small></td><td><button class="button" type="button" data-group-detail="${esc(group.id)}">${group.majors?.length||0}个专业</button></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty-state"><strong>没有匹配的专业组</strong><p>请放宽筛选，或取消“只看我的备选”。</p></div></td></tr>'}</tbody></table></div>
      <div class="pagination"><button class="button" type="button" data-page="${state.matrix.page-1}" ${state.matrix.page<=1?'disabled':''}>上一页</button><span>第 ${state.matrix.page} / ${pages} 页</span><button class="button" type="button" data-page="${state.matrix.page+1}" ${state.matrix.page>=pages?'disabled':''}>下一页</button></div>`;
  }

  function renderPhysical(){
    const f=state.record.physical,p=state.record.profile;const height=Number(f.height),weight=Number(f.weight),bmi=height>0&&weight>0?(weight/((height/100)**2)).toFixed(1):'—';
    return`${pageHead('PHYSICAL CHECK','身体条件核验','这是报考前自查，不替代军检、公安体检、航海体检或院校复检。','<button class="button primary" type="button" id="saveNow">保存自查</button>')}
      <div class="privacy-note"><b>先选具体通道，再看标准</b><p>同一学校不同专业、同一类别不同院校的标准可能不同。中警院裸眼视力4.7/4.8、上海海关体检等材料存在冲突，系统统一标记等待2026官方核验。</p></div>
      <section class="profile-layout"><form id="physicalForm" class="form-panel"><section class="form-section"><h2>一、基础体格</h2><p>BMI仅按填写数据计算，公安等项目仍以现场测量为准。</p><div class="form-grid"><label class="field"><span>身高（cm）</span><input data-field="physical.height" inputmode="decimal" value="${esc(f.height)}"></label><label class="field"><span>体重（kg）</span><input data-field="physical.weight" inputmode="decimal" value="${esc(f.weight)}"><small class="field-hint">当前 BMI：${bmi}</small></label><label class="field"><span>听力自查</span><select data-field="physical.hearing"><option value="">请选择</option><option value="normal" ${f.hearing==='normal'?'selected':''}>自查正常</option><option value="concern" ${f.hearing==='concern'?'selected':''}>可能异常</option><option value="pending" ${f.hearing==='pending'?'selected':''}>待检查</option></select></label><label class="field"><span>官方/专项体检</span><select data-field="physical.physicalExam"><option value="">请选择</option><option value="not_started" ${f.physicalExam==='not_started'?'selected':''}>未开始</option><option value="scheduled" ${f.physicalExam==='scheduled'?'selected':''}>已预约</option><option value="passed" ${f.physicalExam==='passed'?'selected':''}>已通过</option><option value="failed" ${f.physicalExam==='failed'?'selected':''}>未通过</option><option value="review" ${f.physicalExam==='review'?'selected':''}>需复查</option></select></label></div></section>
        <section class="form-section"><h2>二、视力与色觉</h2><p>请输入体检表或规范视力表数据；“自觉看得清”不能替代检查。</p><div class="form-grid"><label class="field"><span>左眼裸眼视力</span><input data-field="physical.nakedVisionLeft" inputmode="decimal" value="${esc(f.nakedVisionLeft)}" placeholder="例如 4.8"></label><label class="field"><span>右眼裸眼视力</span><input data-field="physical.nakedVisionRight" inputmode="decimal" value="${esc(f.nakedVisionRight)}" placeholder="例如 4.8"></label><label class="field"><span>矫正视力（较低眼）</span><input data-field="physical.correctedVision" inputmode="decimal" value="${esc(f.correctedVision)}"></label><label class="field"><span>色觉</span><select data-field="physical.colorVision"><option value="">请选择</option><option value="normal" ${f.colorVision==='normal'?'selected':''}>正常</option><option value="abnormal" ${f.colorVision==='abnormal'?'selected':''}>色弱/色盲</option><option value="pending" ${f.colorVision==='pending'?'selected':''}>待检查</option></select></label><label class="field wide"><span>眼睛激光手术日期</span><input type="date" data-field="physical.laserSurgeryDate" value="${esc(f.laserSurgeryDate)}"><small class="field-hint">军校资料线索要求术后满半年；不要采用“视力达标即可绕过期限”的说法。</small></label></div></section>
        <section class="form-section"><h2>三、其他需带到线下核验的问题</h2><p>只写“需复查的项目”，不在普通页面存完整病史。</p><label class="field"><span>复查事项</span><textarea data-field="physical.otherNotes" placeholder="例如：膝关节、脊柱、瘢痕等需向体检机构咨询。">${esc(f.otherNotes)}</textarea></label></section></form>
        <aside class="sticky-summary"><div class="summary-card"><span class="eyebrow">CATEGORY RESULTS</span><h2>七类资格状态</h2><div class="summary-list">${categories().map(category=>{const result=qualificationFor(category.id);return`<div class="summary-row"><span>${esc(category.title)}</span><b>${esc(result.label)}</b></div>`}).join('')}</div><p class="summary-note">“明显不符合”是按当前二手资料线索发现的冲突；若2026官方标准变化，应以正式文件和现场结论更新。</p></div></aside></section>`;
  }

  function renderPrecheck(){
    const items=[
      ['political_self_check','政治考察要求自查','只确认是否已阅读条件，不记录亲属案件、服刑或境外关系详情。'],['political_form','政治考察表办理','按2026正式通知下载、盖章、提交。'],['pre_registration','前置报名/预报名','公安、招飞等可能在志愿填报前完成。'],['interview','面试准备与通知','确认时间、地点、证件和复议规则。'],['fitness_test','体能测试','项目与标准必须来自2026官方文字通知。'],['medical_exam','专项体检/军检','保存办理状态和官方结论，不自行替代。'],['psychological_test','心理检测','军校、消防、招飞等可能涉及。'],['oral_exam','外语口试','外交、小语种等逐校核验。'],['county_review','县区资格审核','地方专项、教师、医学定向按县区公示。'],['agreement_review','协议原文审阅','服务期、地点、升学、违约与退出条款逐条确认。']
    ];
    return`${pageHead('PREQUALIFICATION','政审与前置资格','把容易错过的办理事项变成状态清单，同时保护学生和家庭敏感信息。','<button class="button primary" type="button" id="saveNow">保存状态</button>')}<div class="privacy-note"><b>隐私边界</b><p>本页只保存“未开始、准备中、已提交、已通过”等办理状态。亲属违法、服刑、境外关系、疾病史原文等高度敏感详情，请在授权场景下直接交给主管部门，不录入普通学生档案。</p></div><section class="panel"><div class="panel-head"><div><h2>前置资格办理台</h2><p>具体时间、表格和受理单位等待2026江苏及主管部门通知。</p></div></div><div class="status-list">${items.map(([id,title,detail])=>`<div class="status-row"><div><b>${esc(title)}</b><p>${esc(detail)}</p></div><select data-check-id="${esc(id)}" aria-label="${esc(title)}状态">${statusOptions(state.record.qualificationChecks[id]||'')}</select></div>`).join('')}</div></section>`;
  }

  function agreementCards(){return[
    {id:'rural_teacher',title:'江苏乡村教师定向',category:'乡村教师',years:'连续服务5年',place:'本县乡村学校',education:'服务期内全日制升学受限',exit:'未到岗或未满期可能涉及违约金、考研与事业单位应聘限制',note:'本县报本县；培养期间不迁户口、不变户籍、不变专业。不得与部属公费师范6年混写。'},
    {id:'rural_medical',title:'农村订单定向医学生',category:'医学定向',years:'基层服务6年',place:'乡镇卫生院或村卫生室',education:'3年全科规培计入服务期（按资料线索）',exit:'返还补助、补缴费用、升学就业限制及信用记录风险',note:'编制岗位并非人人自动获得；二手材料称最高不超过招生人数80%，必须等正式协议。'},
    {id:'nuclear_targeted',title:'核工程／军工等特殊定向',category:'其他特殊培养',years:'5年/6年材料冲突',place:'协议约定单位及岗位',education:'转专业与升学限制逐协议核对',exit:'服务期、费用与证书说法均不可凭讲座下结论',note:'必须保存2026协议单位、服务期、资助、深造、转专业和违约原文。'},
    {id:'military_service',title:'军校培养与军籍路径',category:'军事院校',years:'按培养与服役制度',place:'组织分配与岗位需要',education:'培养、转段和深造按军队制度',exit:'入校复检、军籍、纪律和服役义务均是核心边界',note:'不能只把军校理解为免学费或就业保障；先确认学生真正接受军队生活。'}
  ]}
  function renderAgreement(){return`${pageHead('AGREEMENT COST','协议与代价工作台','把“免费、定向、有岗”等宣传词拆成服务期、地域、升学、岗位竞争和违约责任。','<button class="button primary" type="button" id="saveNow">保存接受度</button>')}<div class="baseline-alert"><b>先看协议，再谈收益</b><p>本页为二手资料结构化提醒，不构成合同解释。正式填报前应由学生和监护人共同阅读2026协议原文。</p></div><section class="agreement-grid">${agreementCards().map(card=>`<article class="agreement-card"><span class="badge orange">${esc(card.category)}</span><h3>${esc(card.title)}</h3><p>${esc(card.note)}</p><div class="fact-grid"><div class="fact"><span>服务期</span><b>${esc(card.years)}</b></div><div class="fact"><span>地点</span><b>${esc(card.place)}</b></div><div class="fact"><span>升学</span><b>${esc(card.education)}</b></div><div class="fact"><span>退出代价</span><b>${esc(card.exit)}</b></div></div><label class="field" style="margin-top:12px"><span>当前接受度</span><select data-agreement-id="${esc(card.id)}"><option value="">未判断</option><option value="accept" ${state.record.agreements[card.id]==='accept'?'selected':''}>可接受</option><option value="review" ${state.record.agreements[card.id]==='review'?'selected':''}>需看正式协议</option><option value="reject" ${state.record.agreements[card.id]==='reject'?'selected':''}>不接受</option></select></label></article>`).join('')}</section>`}

  function timelineItems(){return Array.isArray(GUIDE.timeline)&&GUIDE.timeline.length?GUIDE.timeline:Array.isArray(RULES.timeline)?RULES.timeline:[]}
  function renderTimeline(){
    const items=timelineItems();
    return`${pageHead('REFERENCE TIMELINE','时间与材料提醒','资料中的日期均为往年参考节点，未确认前不能当作2026官方日程。','<button class="button primary" type="button" id="saveNow">保存节点状态</button>')}<div class="source-policy"><b>时间口径</b> 页面保留“参考”字样；2026江苏考试院、主管部门或院校发布正式通知后，再把官方日期、链接和核验人写入复核台。</div><section class="timeline">${items.map(item=>{const value=state.record.tasks[item.id]===true?'done':state.record.tasks[item.id]||'pending';const resolved=value==='done'||value==='not_applicable';return`<article class="timeline-item ${resolved?'done':''}"><header><h3>${esc(item.title)}</h3><time>${esc(item.window||item.time||'待通知')}</time></header><p>${esc(item.detail||item.description||'')}</p><label class="task-check"><span>该学生节点状态</span><select class="task-state-select" data-task-id="${esc(item.id)}"><option value="pending" ${value==='pending'?'selected':''}>待确认/待办理</option><option value="done" ${value==='done'?'selected':''}>已完成</option><option value="not_applicable" ${value==='not_applicable'?'selected':''}>本年度或该学生不适用</option></select></label><small class="field-hint">${esc(item.sourceTitle||item.sourceId||'用户提供资料')}｜${esc(item.verificationStatus||'待2026官方核验')}</small></article>`}).join('')||'<div class="empty-state"><strong>时间线资料未加载</strong><p>请检查 rules-2026.js 与 data.js。</p></div>'}</section>`;
  }

  function careerPaths(){return Array.isArray(GUIDE.careerPaths)&&GUIDE.careerPaths.length?GUIDE.careerPaths:[
    {id:'military',label:'军队培养与组织分配',examples:['军事院校'],guaranteeLevel:'组织规则约束，不等于自由择业'},
    {id:'police',label:'统一招录考试路径',examples:['公安联考','司法招警'],guaranteeLevel:'只覆盖明确院校专业身份，仍须参加考试'},
    {id:'civil',label:'国考/公务员择优',examples:['消防干部','海关岗位'],guaranteeLevel:'竞争性考试，不包录用'},
    {id:'contract',label:'协议定向服务',examples:['乡村教师','定向医学生'],guaranteeLevel:'岗位和编制以协议及招聘为准'},
    {id:'market',label:'自主择业',examples:['航海类','特色院校普通就业'],guaranteeLevel:'不承诺固定就业率'}
  ]}
  function renderCareer(){return`${pageHead('CAREER ENDPOINT','职业终点地图','把学校光环拆成真实的毕业通道：分配、联考、国考、协议定向或自主就业。')}<div class="baseline-alert"><b>所有终点都不能统一写成“包分配”</b><p>消防干部率、海关就业率、定向医学编制等三份材料互相冲突；系统不展示固定概率。</p></div><section class="career-grid">${careerPaths().map((path,index)=>`<article class="career-card"><span class="badge ${index===0?'green':index===1?'blue':'orange'}">终点 ${index+1}</span><h3>${esc(path.label||path.title)}</h3><p>${esc(path.guaranteeLevel||path.description||'以2026官方文件与招聘结果为准')}</p><div class="career-route">${(path.examples||path.routes||[]).map((item,i,arr)=>`<span>${esc(item)}</span>${i<arr.length-1?'<i>→</i>':''}`).join('')}</div></article>`).join('')}</section>`}

  function sources(){return Array.isArray(GUIDE.sources)&&GUIDE.sources.length?GUIDE.sources:Array.isArray(RULES.sources)?RULES.sources:[]}
  function conflicts(){return Array.isArray(GUIDE.conflicts)&&GUIDE.conflicts.length?GUIDE.conflicts:Array.isArray(RULES.conflicts)?RULES.conflicts:[]}
  function renderSources(){
    const conflictStatusOptions=current=>[['','未复核'],['researching','查找2026官方文件'],['conflict_unresolved','官方文件仍未关闭冲突'],['official_verified','已用2026官方文件人工核验'],['not_applicable','该学生不适用']].map(([value,label])=>`<option value="${value}" ${current===value?'selected':''}>${label}</option>`).join('');
    return`${pageHead('SOURCE REVIEW','来源与冲突复核','资料可以帮助建立研究清单，但只有2026官方文件可以关闭规则冲突。')}
      <div class="source-policy"><b>当前统一状态：等待2026官方核验</b> 三份Markdown均为用户提供的二手整理；Excel为用户提供的数据工作簿。系统保留年份、江苏、来源类型、核验状态与冲突组，不把二手结论伪装成官方政策。</div>
      <section class="source-grid">${sources().map(source=>`<article class="source-card"><h3>${esc(source.title||source.sourceTitle)}</h3><p>${esc(source.scope||source.notice||'')}</p><div class="source-meta"><span class="badge blue">${esc(source.sourceType)}</span><span class="badge orange">${esc(source.sourceYear||source.year||'年份待核')}</span><span class="badge orange">${esc(source.verificationStatus)}</span></div></article>`).join('')}<article class="source-card"><h3>${esc(GROUP_DATA.meta?.sourceTitle||'2026 提前批次分析.xlsx')}</h3><p>499组、1687条专业明细，其中高校专项151组、综评A 23组为独立通道。2026组投档线与2025专业最低录取分不同口径；23个综评A组分位不适用。</p><div class="source-meta"><span class="badge blue">用户提供工作簿</span><span class="badge orange">待官方逐项复核</span></div></article></section>
      <section class="panel" style="margin-top:16px"><div class="panel-head"><div><h2>冲突复核台（${conflicts().length}组）</h2><p>人工复核记录不会自动把规则改成“已通过”；仍须归档正式文件。</p></div></div><div class="conflict-list">${conflicts().map(conflict=>{const officialUrl=/^https?:\/\//i.test(String(conflict.officialUrl||''))?conflict.officialUrl:'';return`<article class="conflict-row"><b>${esc(conflict.title)}</b><p>${esc((conflict.claims||[]).map(claim=>typeof claim==='string'?claim:claim.text||claim.claim).filter(Boolean).join(' ↔ ')||conflict.handling||'来源表述不一致')}</p><small class="field-hint">冲突组：${esc(conflict.id)}｜来源：${esc(conflict.sourceTitle||conflict.sourceId||'用户提供资料')}｜原文：${esc(conflict.sourceLines||'待定位')}｜级别：${esc(conflict.severity||conflict.riskLevel||'需人工复核')}</small><small class="field-hint">处理：${esc(conflict.handling||'等待2026官方文件关闭')}｜${esc(conflict.verificationStatus||'source_conflict_needs_2026_official_verification')}${officialUrl?`｜<a href="${esc(officialUrl)}" target="_blank" rel="noopener">官方核验链接</a>`:''}</small><label class="field" style="margin-top:9px"><span>该学生人工复核记录</span><select data-source-check-id="${esc(conflict.id)}">${conflictStatusOptions(state.record.sourceChecks[conflict.id]||'')}</select></label></article>`}).join('')}</div></section>`;
  }

  function getByPath(obj,path){return path.split('.').reduce((value,key)=>value?.[key],obj)}
  function setByPath(obj,path,value){const keys=path.split('.');let target=obj;keys.slice(0,-1).forEach(key=>{if(!target[key]||typeof target[key]!=='object')target[key]={};target=target[key]});target[keys.at(-1)]=value}
  function fieldValue(element){if(element.type==='checkbox')return element.checked;if(element.type==='number')return element.value;return element.value}
  function bindDataFields(container=document){container.querySelectorAll('[data-field]').forEach(element=>{const handler=event=>{const path=element.dataset.field;if(path==='profile.electivesText'){state.record.profile.electives=unique(String(element.value||'').split(/[、,，+\s]+/).map(value=>value.trim()))}else setByPath(state.record,path,fieldValue(element));queueSave();if(event.type==='change'&&['profile.birthDate','physical.height','physical.weight'].includes(path))render()};element.addEventListener('change',handler);if(element.tagName==='TEXTAREA'||element.tagName==='INPUT'&&element.type!=='date')element.addEventListener('input',handler)})}

  function openDrawer(title,eyebrow,html){$('#drawerTitle').textContent=title;$('#drawerEyebrow').textContent=eyebrow;$('#drawerBody').innerHTML=html;$('#detailDrawer').classList.add('open');$('#detailDrawer').setAttribute('aria-hidden','false');$('#drawerScrim').hidden=false;bindDrawer()}
  function closeDrawer(){const drawer=$('#detailDrawer');drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');$('#drawerScrim').hidden=true}
  function rulesForCategory(categoryId){const aliases={police:['public-security','judicial'],medical:['rural-medical'],other:['other'],military:['military'],maritime:['maritime'],'local-special':['local-special'],'rural-teacher':['rural-teacher']};const prefixes=aliases[categoryId]||[categoryId];return(Array.isArray(RULES.rules)?RULES.rules:[]).filter(rule=>prefixes.some(prefix=>String(rule.categoryId||'').startsWith(prefix))).slice(0,22)}
  function showCategoryDetail(categoryId){const category=categoryById(categoryId),rules=rulesForCategory(categoryId);openDrawer(category.title,'CATEGORY DETAIL',`<section class="detail-section"><div class="result-banner" data-state="${esc(qualificationFor(categoryId).state)}"><div><strong>${esc(qualificationFor(categoryId).label)}</strong><p>${esc(qualificationFor(categoryId).detail)}</p></div></div><p>${esc(category.summary)}</p></section><section class="detail-section"><h3>决策问题</h3><p>${esc(category.decisionQuestion||category.qualification)}</p></section><section class="detail-section"><h3>资料规则线索（全部待2026官方核验）</h3><div class="major-list">${rules.map(rule=>`<article class="major-row"><b>${esc(rule.topic)}</b><small>${esc(rule.statement)}</small><small>${esc(rule.sourceTitle||rule.sourceId)}｜${esc(rule.sourceLines)}｜${esc(rule.verificationStatus)}</small></article>`).join('')||'<p>请按具体院校和专业读取2026官方文件。</p>'}</div></section><section class="detail-section"><h3>职业与代价</h3><p>${esc(category.career)}</p><p>${esc(category.cost)}</p></section>`)}
  function formatMoney(value){if(value===null||value===undefined||value==='')return'未维护';if(Number(value)===0)return'源表为0，待核';if(typeof value==='number')return`${value}元/年`;return String(value)}
  function showGroupDetail(groupId){const group=GROUPS.find(item=>item.id===groupId);if(!group)return;const fit=fitGroup(group),selected=state.record.selectedGroupKeys.includes(group.id);openDrawer(group.groupName,'PROFESSIONAL GROUP',`<section class="detail-section"><div class="source-meta"><span class="badge ${fit.state==='fail'?'red':fit.state==='separate'?'orange':'blue'}">${esc(fit.label)}</span> <span class="badge orange">${esc(group.verificationStatus)}</span></div><p>${group.separateTrack?'该记录属于高校专项或综评A的独立批次位置，不进入普通本科提前批推荐池。':'资格状态优先于历史分数；此处不生成录取概率。'}</p><button class="button ${selected?'danger':'primary'}" type="button" data-drawer-group-toggle="${esc(group.id)}">${selected?'移出我的备选':'加入我的备选'}</button></section><section class="detail-section"><h3>专业组概况</h3><div class="detail-grid"><div class="detail-cell"><span>学校</span><b>${esc(group.school)}</b></div><div class="detail-cell"><span>代码</span><b>${esc(group.code)}</b></div><div class="detail-cell"><span>类别</span><b>${esc(group.categoryRaw)}</b></div><div class="detail-cell"><span>选科</span><b>${esc(group.subjectType)}｜${esc(group.elective)}</b></div><div class="detail-cell"><span>性别计划</span><b>${esc(group.gender)}</b></div><div class="detail-cell"><span>2026计划</span><b>${esc(group.plan2026)}</b></div></div></section><section class="detail-section"><h3>分数与位次（参考口径）</h3><div class="detail-grid"><div class="detail-cell"><span>2026组投档</span><b>${group.score2026??'不适用/缺失'}分｜${group.rank2026?`位次${group.rank2026}`:'位次缺失'}</b></div><div class="detail-cell"><span>2025组内专业最低</span><b>${group.score2025??'缺失'}分｜${group.rank2025?`位次${group.rank2025}`:'位次缺失'}</b></div><div class="detail-cell"><span>参考分差</span><b>${group.scoreDelta===null?'不可比':`${group.scoreDelta>0?'+':''}${group.scoreDelta}分`}</b></div></div><p>2026是专业组投档线，2025是组内专业录取最低分，两者不是同口径；分差和位次变化只能作历史参考。</p></section><section class="detail-section"><h3>组内专业（${group.majors?.length||0}）</h3><div class="major-list">${(group.majors||[]).map(major=>`<article class="major-row"><b>${esc(major.code)} ${esc(major.name)}</b><small>2026计划 ${major.plan2026??'—'}｜学制 ${esc(major.duration||'待核')}｜学费 ${esc(formatMoney(major.tuition))}</small><small>2025最低 ${major.low2025??'—'}｜位次 ${major.rank2025??'—'}</small></article>`).join('')}</div></section><section class="detail-section"><h3>数据来源</h3><p>${esc(GROUP_DATA.meta?.sourceTitle||'2026 提前批次分析.xlsx')}｜用户提供工作簿｜待与2026江苏官方招生计划及投档公告逐项复核。</p></section>`)}
  function bindDrawer(){$('[data-drawer-group-toggle]')?.addEventListener('click',event=>{toggleGroup(event.currentTarget.dataset.drawerGroupToggle);showGroupDetail(event.currentTarget.dataset.drawerGroupToggle)})}
  function toggleGroup(groupId,checked){const set=new Set(state.record.selectedGroupKeys||[]);const shouldAdd=checked===undefined?!set.has(groupId):checked;shouldAdd?set.add(groupId):set.delete(groupId);state.record.selectedGroupKeys=[...set];const tableInput=document.querySelector(`[data-group-select="${groupId}"]`);if(tableInput)tableInput.checked=shouldAdd;queueSave(shouldAdd?'已加入备选':'已移出备选');updateStudentHeader()}

  function bindView(){
    bindDataFields($('#appView'));
    $$('[data-go-view]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.goView)));
    $('#retryWorkspace')?.addEventListener('click',async()=>{try{await loadWorkspaceData()}catch(err){returnToLogin('登录状态已过期')}});
    $('#retrySyncConflict')?.addEventListener('click',refreshSyncConflictCloud);
    $('#useCloudVersion')?.addEventListener('click',useCloudVersion);
    $('#downloadCurrentConflict')?.addEventListener('click',downloadCurrentConflict);
    $('#saveNow')?.addEventListener('click',()=>saveRecord('已保存'));
    $$('input[name=specialControlLine]').forEach(input=>input.addEventListener('change',()=>{state.record.profile.specialControlLine=input.value;queueSave();render()}));
    $$('[data-category-id]').forEach(button=>button.addEventListener('click',()=>{state.mapCategory=button.dataset.categoryId;state.record.mapChoices.category=state.mapCategory;queueSave();render()}));
    $$('[data-category-detail]').forEach(button=>button.addEventListener('click',()=>showCategoryDetail(button.dataset.categoryDetail)));
    $('[data-map-to-matrix]')?.addEventListener('click',event=>{state.matrix.category=event.currentTarget.dataset.mapToMatrix||'';state.matrix.page=1;navigate(state.matrix.category?'matrix':state.mapCategory==='rural-teacher'?'agreement':'precheck')});
    const matrixQuery=$('#matrixQuery');
    if(matrixQuery){
      let composing=false;
      const scheduleMatrixSearch=value=>{state.matrix.q=value;state.matrix.page=1;clearTimeout(state.matrix.searchTimer);state.matrix.searchTimer=setTimeout(()=>{state.matrix.searchTimer=null;render();const next=$('#matrixQuery');if(next){next.focus({preventScroll:true});const end=next.value.length;next.setSelectionRange?.(end,end)}},220)};
      matrixQuery.addEventListener('compositionstart',()=>{composing=true});
      matrixQuery.addEventListener('compositionend',event=>{composing=false;scheduleMatrixSearch(event.target.value)});
      matrixQuery.addEventListener('input',event=>{if(composing||event.isComposing)return;scheduleMatrixSearch(event.target.value)});
    }
    [['#matrixSubject','subject'],['#matrixCategory','category'],['#matrixGender','gender'],['#matrixElective','elective']].forEach(([selector,key])=>$(selector)?.addEventListener('change',event=>{state.matrix[key]=event.target.value;state.matrix.page=1;render()}));
    $('#toggleSelected')?.addEventListener('click',()=>{state.matrix.selectedOnly=!state.matrix.selectedOnly;state.matrix.page=1;render()});
    $$('[data-page]').forEach(button=>button.addEventListener('click',()=>{state.matrix.page=Math.max(1,Number(button.dataset.page)||1);render();$('#appView').focus()}));
    $$('[data-group-select]').forEach(input=>input.addEventListener('change',()=>toggleGroup(input.dataset.groupSelect,input.checked)));
    $$('[data-group-detail]').forEach(button=>button.addEventListener('click',()=>showGroupDetail(button.dataset.groupDetail)));
    $$('[data-check-id]').forEach(select=>select.addEventListener('change',()=>{state.record.qualificationChecks[select.dataset.checkId]=select.value;queueSave()}));
    $$('[data-agreement-id]').forEach(select=>select.addEventListener('change',()=>{state.record.agreements[select.dataset.agreementId]=select.value;queueSave()}));
    $$('[data-source-check-id]').forEach(select=>select.addEventListener('change',()=>{state.record.sourceChecks[select.dataset.sourceCheckId]=select.value;queueSave()}));
    $$('[data-task-id]').forEach(select=>select.addEventListener('change',()=>{state.record.tasks[select.dataset.taskId]=select.value;queueSave();render()}));
  }
  function navigate(view){state.view=view;render();window.scrollTo({top:0,behavior:'smooth'});$('#appView')?.focus({preventScroll:true})}

  function openStudentModal(){
    const backupCount=listConflictBackups().length,modal=$('#modal');modal.innerHTML=`<div class="modal-head"><h2 id="modalTitle">选择学生</h2><button class="icon-button" type="button" data-close-modal aria-label="关闭">×</button></div><div class="modal-body">${backupCount?`<div class="baseline-alert"><b>当前学生有 ${backupCount} 份本机冲突备份</b><p>备份不会自动覆盖云端；需要查看原稿时可先导出 JSON 留存。</p><button class="button" type="button" id="downloadStoredConflicts">导出冲突备份</button></div>`:''}<div class="student-list">${state.students.map(student=>`<button class="student-option" type="button" data-student-id="${esc(student.id)}"><span class="student-avatar">${esc(student.name?.slice(0,1)||'学')}</span><span><b>${esc(student.name||'未命名学生')}</b><small>${esc(normalizeSubject(student.subject_type)||'选科待补')}｜${esc(studentValue(student,'gaokao_score','estimated_score','score')||'分数待补')}分</small></span><i>${student.id===state.currentStudent?.id?'当前':'选择'}</i></button>`).join('')||'<div class="empty-state"><strong>暂无学生</strong><p>请先前往学生档案建立记录。</p></div>'}</div></div><div class="modal-actions"><a class="button" href="../students/index.html">管理学生档案</a><button class="button" type="button" data-close-modal>取消</button></div>`;$('#modalMask').hidden=false;$$('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModal));$('#downloadStoredConflicts')?.addEventListener('click',downloadStoredConflicts);$$('[data-student-id]').forEach(button=>button.addEventListener('click',()=>switchStudent(button.dataset.studentId)));
  }
  function closeModal(){$('#modalMask').hidden=true}
  async function switchStudent(studentId){
    if(state.loadingStudent||studentId===state.currentStudent?.id){closeModal();return}const student=state.students.find(item=>item.id===studentId);if(!student)return;state.loadingStudent=true;let previous=null;
    try{await flushPendingSave();if(blockUnsafeConflictExit())return;previous={student:state.currentStudent,record:state.record,cloudReady:state.cloudReady,cloudUpdatedAt:state.cloudUpdatedAt,cloudRecord:state.cloudRecord,localBaseCloudUpdatedAt:state.localBaseCloudUpdatedAt,localBaseKnown:state.localBaseKnown,localDirty:state.localDirty,needsSync:state.needsSync,syncConflict:state.syncConflict,conflictExported:state.conflictExported,recordWritable:state.recordWritable,recordLoadError:state.recordLoadError,localDraftReady:state.localDraftReady,mapCategory:state.mapCategory,matrix:clone(state.matrix)};setSaveState('saving','正在切换');const loaded=await loadRecordData(student);saveCurrentStudent(student);applyLoadedRecord(student,loaded);closeModal();render();if(state.syncConflict)setSaveState('error','同步冲突');else if(state.needsSync&&state.cloudReady){setSaveState('saving','正在同步本机草稿');await saveRecord('')}else setSaveState(state.cloudReady?'saved':'error',state.cloudReady?'云端已连接':state.localDraftReady?'本机草稿':'无法保存');toast(`已切换到 ${student.name}`)}catch(err){if(previous){state.currentStudent=previous.student;state.record=previous.record;state.cloudReady=previous.cloudReady;state.cloudUpdatedAt=previous.cloudUpdatedAt;state.cloudRecord=previous.cloudRecord;state.localBaseCloudUpdatedAt=previous.localBaseCloudUpdatedAt;state.localBaseKnown=previous.localBaseKnown;state.localDirty=previous.localDirty;state.needsSync=previous.needsSync;state.syncConflict=previous.syncConflict;state.conflictExported=previous.conflictExported;state.recordWritable=previous.recordWritable;state.recordLoadError=previous.recordLoadError;state.localDraftReady=previous.localDraftReady;state.mapCategory=previous.mapCategory;state.matrix=previous.matrix;saveCurrentStudent(previous.student);render();setSaveState(state.syncConflict?'error':state.needsSync?'error':state.cloudReady?'saved':'error',state.syncConflict?'同步冲突':state.needsSync?'待同步':state.cloudReady?'已保存':state.localDraftReady?'本机草稿':'无法保存')}if(err.authExpired||err.status===401)returnToLogin('登录状态已过期');else toast('切换失败：'+humanError(err))}finally{state.loadingStudent=false}
  }
  function bindShell(){
    $$('.nav-item').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.view)));
    $('#studentPicker').addEventListener('click',()=>{if(!blockUnsafeConflictExit())openStudentModal()});$('#logoutBtn').addEventListener('click',()=>{if(!blockUnsafeConflictExit())returnToLogin('已退出登录')});$('#closeDrawer').addEventListener('click',closeDrawer);$('#drawerScrim').addEventListener('click',closeDrawer);$('#modalMask').addEventListener('click',event=>{if(event.target===$('#modalMask'))closeModal()});
    document.addEventListener('click',event=>{if(!hasUnsafeMemoryConflict())return;const link=event.target.closest?.('a[href]');if(!link||link.hasAttribute('download'))return;event.preventDefault();blockUnsafeConflictExit()},true);
    window.addEventListener('keydown',event=>{if(event.key==='Escape'){closeDrawer();closeModal()}});window.addEventListener('message',handleAuthMessage);window.addEventListener('beforeunload',event=>{if(hasUnsafeMemoryConflict()){event.preventDefault();event.returnValue=''}});window.addEventListener('pagehide',()=>{if(state.recordWritable&&!state.syncConflict)saveLocalDraft(undefined,undefined,{dirty:state.localDirty})});
  }
  async function init(){
    bindShell();const localPreview=['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).get('preview')==='1';
    if(localPreview){const previewStudent={id:'local-preview-student',name:'预览学生',subject_type:'physics',subject_choices:['化学','生物'],estimated_score:612,estimated_rank:17800};state.auth={accessToken:'local-preview',refreshToken:'',user:{id:'local-preview-user',email:'preview@local'}};state.students=[previewStudent];state.currentStudent=previewStudent;state.record=defaultRecord();state.record.profile={...state.record.profile,...profileFromStudent(previewStudent),gender:'male',birthDate:'2008-05-16',maritalStatus:'unmarried',graduateType:'fresh',specialControlLine:'yes',hukouCounty:'盐城市示例县',ruralHukou:'yes',hukouYears:'8',schoolYears:'3',ordinaryBaseline:'普通批优先江苏公办院校的电子信息类，不接受无法转专业和长期地域锁定。',serviceAcceptance:'uncertain'};state.record.physical={...state.record.physical,height:'175',weight:'68',nakedVisionLeft:'4.8',nakedVisionRight:'4.8',correctedVision:'5.0',colorVision:'normal',physicalExam:'not_started'};state.matrix.subject='物理类';state.cloudReady=false;state.recordWritable=true;showAuthCover(false);render();setSaveState('error','本机预览');return}
    const stored=storageJSON(AUTH_STORAGE_KEY,null);if(!stored?.accessToken||!stored?.user?.id){showAuthCover(true);return}state.auth={accessToken:stored.accessToken,refreshToken:stored.refreshToken||'',user:stored.user};
    try{await ensureProfile(state.auth.user);await loadWorkspaceData();showAuthCover(false)}catch(err){returnToLogin(err.authExpired?'登录状态已过期':'账号或网络校验失败：'+humanError(err))}
  }
  init();
})();
