(function(){
'use strict';
const SUPABASE_URL='https://qnspmqsrbjcgrgpqkzgl.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_pVjv5t2S338SsCW98VvwpA_PcpXBL7V';
const AUTH_STORAGE_KEY='js-plan-auth-v1';
const BUCKET='planning-public';
const FALLBACK_ITEMS=[
  {id:'sample-1',title:'江苏新高考志愿填报系统使用说明',category:'讲座资料',summary:'示例资料：用于演示图文区列表、分类筛选与 PDF 在线查看入口。正式资料请登录后上传。',file_url:'',file_name:'示例资料',created_at:new Date().toISOString(),published:true,source:'sample'},
  {id:'sample-2',title:'中外合作项目核对清单',category:'中外合作',summary:'示例资料：后续可上传 985/211 中外合作项目 PDF，公开给所有用户查看。',file_url:'',file_name:'示例资料',created_at:new Date().toISOString(),published:true,source:'sample'}
];
let auth={accessToken:'',refreshToken:'',user:null};
let items=[];
let selectedItem=null;
const $=sel=>document.querySelector(sel);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function storageJSON(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(e){return fallback;}}
function loadSavedAuth(){const data=storageJSON(AUTH_STORAGE_KEY,{}); if(data?.accessToken&&data?.user)auth={accessToken:data.accessToken,refreshToken:data.refreshToken||'',user:data.user};}
function saveAuth(){localStorage.setItem(AUTH_STORAGE_KEY,JSON.stringify({accessToken:auth.accessToken||'',refreshToken:auth.refreshToken||'',user:auth.user||null}));}
function clearAuth(){localStorage.removeItem(AUTH_STORAGE_KEY);auth={accessToken:'',refreshToken:'',user:null};}
function authHeaders(extra={}){return {apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${auth.accessToken||SUPABASE_ANON_KEY}`,'Content-Type':'application/json',...extra};}
function publicHeaders(extra={}){return {apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json',...extra};}
async function apiFetch(path,options={}){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:options.auth?authHeaders(options.headers||{}):publicHeaders(options.headers||{})});if(!res.ok)throw new Error(await res.text());return res.status===204?null:res.json();}
function setStatus(text,isError=false){const el=$('#uploadStatus'); if(el){el.textContent=text||''; el.classList.toggle('danger',Boolean(isError));}}
function updateAccountUI(){const pill=$('#accountPill');const logout=$('#logoutBtn');const login=$('#loginArea');const uploadBtn=$('#uploadBtn');if(auth.user){pill.textContent=`已登录：${(auth.user.email||'账号').split('@')[0]}`;logout.classList.remove('hidden');login.innerHTML='<span class="status">当前账号可上传公开资料。</span>';if(uploadBtn)uploadBtn.disabled=false;}else{pill.textContent='未登录';logout.classList.add('hidden');login.innerHTML='<input id="loginEmail" type="email" placeholder="邮箱"><input id="loginPwd" type="password" placeholder="密码"><button id="loginBtn" class="btn primary" type="button">登录</button>';if(uploadBtn)uploadBtn.disabled=true;$('#loginBtn')?.addEventListener('click',login);}}
async function login(){const email=$('#loginEmail')?.value.trim();const password=$('#loginPwd')?.value;if(!email||!password){setStatus('请先输入邮箱和密码。',true);return;}try{setStatus('正在登录...');const res=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!res.ok)throw new Error(await res.text());const data=await res.json();auth={accessToken:data.access_token,refreshToken:data.refresh_token||'',user:data.user};saveAuth();updateAccountUI();setStatus('登录成功，可以上传 PDF。');}catch(err){setStatus('登录失败：'+err.message,true);}}
function logout(){clearAuth();updateAccountUI();setStatus('已退出登录。');}
function getPdfExtension(name){const m=String(name||'').match(/\.([A-Za-z0-9]{1,8})$/);return m?`.${m[1].toLowerCase()}`:'.pdf';}
function createSafeStoragePath(file){const year=new Date().getFullYear();const userId=String(auth.user?.id||'anonymous').replace(/[^A-Za-z0-9_-]/g,'');const stamp=Date.now();const random=Math.random().toString(36).slice(2,10);const ext=getPdfExtension(file?.name||'document.pdf');return `pdf/${year}/${userId}/${stamp}-${random}${ext}`;}
function formatSize(n){if(!n&&n!==0)return '—'; if(n<1024*1024)return `${Math.round(n/1024)}KB`; return `${(n/1024/1024).toFixed(1)}MB`;}
function shortDate(v){try{return new Date(v).toLocaleDateString('zh-CN');}catch(e){return '—';}}
async function loadItems(){const list=$('#articleList');list.innerHTML='<div class="article-card">正在读取资料...</div>';try{const rows=await apiFetch('planning_articles?select=*&published=eq.true&order=created_at.desc');items=Array.isArray(rows)?rows:[];if(!items.length)items=FALLBACK_ITEMS;renderList();}catch(err){items=FALLBACK_ITEMS;renderList(`<b>资料库暂未连通。</b>请先在 Supabase 执行新版 supabase/schema.sql；当前显示本地示例。错误：${esc(err.message)}`);}}
function filteredItems(){const q=($('#searchInput')?.value||'').trim().toLowerCase();const cat=$('#categoryFilter')?.value||'';return items.filter(x=>{const okCat=!cat||x.category===cat;const text=[x.title,x.summary,x.category,x.file_name].join(' ').toLowerCase();return okCat&&(!q||text.includes(q));});}
function renderList(warning=''){const list=$('#articleList');const rows=filteredItems();if(!rows.length){list.innerHTML=`${warning?`<div class="notice">${warning}</div>`:''}<div class="article-card">没有符合条件的资料。</div>`;return;}list.innerHTML=`${warning?`<div class="notice">${warning}</div>`:''}${rows.map(x=>`<article class="article-card"><div class="article-head"><div><h3>${esc(x.title||'未命名资料')}</h3><div class="article-meta"><span class="tag green">${esc(x.category||'未分类')}</span><span class="tag">${esc(shortDate(x.created_at))}</span><span class="tag">${esc(formatSize(x.file_size))}</span>${x.source==='sample'?'<span class="tag">示例</span>':''}</div></div></div><p>${esc(x.summary||'暂无摘要。')}</p><div class="article-actions">${x.file_url?`<button class="btn primary" type="button" data-view-id="${esc(x.id)}">在线查看</button><a class="btn" href="${esc(x.file_url)}" target="_blank" rel="noopener">下载/新窗口</a>`:'<span class="status">示例卡片暂无 PDF 文件。</span>'}</div></article>`).join('')}`;document.querySelectorAll('[data-view-id]').forEach(btn=>btn.addEventListener('click',()=>showPdf(btn.dataset.viewId)));}
function showPdf(id){selectedItem=items.find(x=>String(x.id)===String(id));if(!selectedItem||!selectedItem.file_url)return;$('#viewerTitle').textContent=selectedItem.title||'PDF 在线查看';const link=$('#openPdfLink');link.href=selectedItem.file_url;link.classList.remove('hidden');$('#viewerBody').innerHTML=`<iframe src="${esc(selectedItem.file_url)}#toolbar=1&navpanes=0" title="${esc(selectedItem.title||'PDF')}" loading="lazy"></iframe>`;}
async function uploadFile(file,path){const res=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${encodeURIComponent(path).replace(/%2F/g,'/')}`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${auth.accessToken}`,'Content-Type':file.type||'application/pdf','x-upsert':'true'},body:file});if(!res.ok)throw new Error(await res.text());return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${path.split('/').map(encodeURIComponent).join('/')}`;}
async function handleUpload(event){event.preventDefault();if(!auth.accessToken||!auth.user){setStatus('请先登录后再上传。',true);return;}const file=$('#fileInput').files?.[0];const title=$('#titleInput').value.trim();const category=$('#categoryInput').value;const summary=$('#summaryInput').value.trim();if(!title||!file){setStatus('请填写标题并选择 PDF 文件。',true);return;}if(!/pdf$/i.test(file.name)&&file.type!=='application/pdf'){setStatus('当前只允许上传 PDF。',true);return;}try{setStatus('正在上传 PDF...');$('#progressBar').style.width='30%';const path=createSafeStoragePath(file);const publicUrl=await uploadFile(file,path);$('#progressBar').style.width='72%';setStatus('PDF 已上传，正在写入公开资料库...');await apiFetch('planning_articles',{method:'POST',auth:true,headers:{Prefer:'return=representation'},body:JSON.stringify({title,category,summary,file_url:publicUrl,file_path:path,file_name:file.name,mime_type:file.type||'application/pdf',file_size:file.size,published:true,created_by:auth.user.id})});$('#progressBar').style.width='100%';setStatus('上传成功，资料已公开发布。');event.target.reset();setTimeout(()=>{$('#progressBar').style.width='0';},800);await loadItems();}catch(err){$('#progressBar').style.width='0';setStatus('上传失败：'+err.message+'。若提示 InvalidKey，通常是旧版本文件名路径含中文或特殊字符；请确认已推送本次修复包，并刷新后重试。若仍失败，再检查 planning-public bucket 与 RLS 策略。',true);}}
function init(){loadSavedAuth();updateAccountUI();$('#logoutBtn')?.addEventListener('click',logout);$('#uploadForm')?.addEventListener('submit',handleUpload);$('#searchInput')?.addEventListener('input',()=>renderList());$('#categoryFilter')?.addEventListener('change',()=>renderList());$('#refreshBtn')?.addEventListener('click',loadItems);loadItems();}
init();
})();
