const resources=[
['《条条大路通罗马》','规划方法','PPTX','多元升学与成长路径'],['好生涯志愿填报指南（想、选、查、排、核）','规划方法','PPTX','志愿填报五步方法'],['升学规划&志愿填报-核心思路与重难点','规划方法','PDF','规划核心框架'],['100 个规划关键词','规划方法','XLSX','咨询与规划概念索引'],['好生涯 26 年升学节点','升学节点','XLSX','2026 届重要时间节点'],
['大学与专业简明指南','专业探索','PDF','大学与专业入门'],['本科专业目录可视化-简明志愿','专业探索','PNG','本科专业全景目录'],['大学专业课程','专业探索','XLSX','大学课程结构'],['专业详解','专业探索','XLSX','专业内容与特点'],['专业就业去向','就业发展','XLSX','专业对应就业方向'],['从高中学科到超级工程','专业探索','XLSX','高中学科与工程领域连接'],['理科生专业评价（分段）','专业探索','XLSX','分段专业评价'],['专业招生人数','招生计划','XLSX','专业招生规模'],['江苏省本科院校专业设置','专业探索','XLSX','江苏高校专业设置'],['专业院校宝典','院校比较','XLSX','专业与院校匹配'],
['江苏高校转专业政策','院校政策','DOCX','高校转专业规则'],['江苏省内高校转专业对比','院校政策','XLSX','省内高校横向对比'],['2025年985招生亮点','院校政策','JPG','985 招生与转专业亮点'],['院校类型表','院校比较','XLSX','院校类型分类'],['院校层次表','院校比较','XLSX','院校层次索引'],['行业特色院校','院校比较','XLSX','行业背景特色院校'],['国家重点学科（仅供参考）','院校比较','XLSX','重点学科参考'],['全国博士点院校一览','深造就业','XLSX','博士点院校分布'],['双非热门工科专业博士点学科评估','深造就业','XLSX','双非工科实力线索'],['2025 年高校预决算','院校比较','XLSX','高校经费观察'],['法学院校就业与科研双维度对比','就业发展','XLSX','法学院校双维比较'],['26 届电网一批次分析','就业发展','XLSX','国家电网就业分析'],
['江苏省 25 年招生计划变化','招生计划','XLSX','2025 招生计划变化'],['2025 年专业分（简版）','分数数据','XLSX','专业录取分简表'],['2025 年理科专业分档次','分数数据','XLSX','理科专业分档'],['25行业特色投档线','分数数据','XLSX','行业特色院校投档线'],['25 江苏高校最低投档线','分数数据','PNG','江苏高校城市分布与投档分'],['26 年新增中外合作','中外合作','XLSX','2026 新增合作项目'],['985中外合作项目（最终版）','中外合作','XLSX','985 合作项目'],['211中外合作项目（最终版）','中外合作','XLSX','211 合作项目'],['中外合作详解','中外合作','XLSX','项目模式与注意事项'],['香港高才通','长期路径','PNG','合资格大学名单'],['志愿填报——地缘文化匹配度分析','院校比较','XLSX','城市与文化适配'],['外省重点院校','院校比较','PDF','外省重点高校'],
['江苏新高考选科指南','规则核验','PDF','选科与专业限制'],['公费师范生（含优师专项）','特殊招生','PDF','公费培养政策'],['军校警校信息','特殊招生','PDF','军警院校报考信息'],['江苏省2026年度考试录用公务员专业参考目录','就业发展','PDF','公务员专业分类参考'],['09-盐城市','就业发展','XLS','2026 盐城公务员职位'],['江苏省2026年度考试录用公务员省级机关职位表','就业发展','XLS','省级机关职位'],['中央机关及其直属机构2026年度考试录用公务员招考简章','就业发展','XLS','国考职位与要求']
].map((r,i)=>({id:i,name:r[0],category:r[1],type:r[2],desc:r[3]}));
const categories=['全部',...new Set(resources.map(r=>r.category))];let active='全部';
const grid=document.querySelector('#resourceGrid'),count=document.querySelector('#resultCount'),search=document.querySelector('#searchInput'),chips=document.querySelector('#categoryChips'),empty=document.querySelector('#emptyState');
function render(){const q=search.value.trim().toLowerCase();const list=resources.filter(r=>(active==='全部'||r.category===active)&&(!q||`${r.name} ${r.category} ${r.desc}`.toLowerCase().includes(q)));count.textContent=list.length;grid.innerHTML=list.map(r=>`<article class="resource"><div class="resource-top"><span class="resource-category">${r.category}</span><span class="resource-type">${r.type}</span></div><h3>${r.name}</h3><p>${r.desc}</p><small>原始资料 · 待逐项核验</small></article>`).join('');empty.hidden=!!list.length}
chips.innerHTML=categories.map((c,i)=>`<button class="${i?'':'active'}" data-category="${c}">${c}</button>`).join('');chips.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;active=b.dataset.category;chips.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()});search.addEventListener('input',render);
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.filter;document.querySelectorAll('#categoryChips button').forEach(x=>x.classList.toggle('active',x.dataset.category===active));render();document.querySelector('#library').scrollIntoView()}));
const tasks=['确定 3 个优先专业方向','列出不能接受的城市与费用边界','比较 2 所学校的转专业政策','核对一个目标专业的核心课程','建立第一版冲稳保院校清单'];let ti=0;document.querySelector('#nextTask').addEventListener('click',()=>{ti=(ti+1)%tasks.length;document.querySelector('#todayTask').textContent=tasks[ti]});
const dialog=document.querySelector('#imageDialog'),dImg=document.querySelector('#dialogImage'),dTitle=document.querySelector('#dialogTitle');document.querySelectorAll('.visual-card').forEach(b=>b.addEventListener('click',()=>{dImg.src=b.dataset.image;dImg.alt=b.dataset.title;dTitle.textContent=b.dataset.title;dialog.showModal()}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
