window.VOLUNTEER_SANDBOX_DATA = {
  "meta": {
    "generatedAt": "2026-07-11T22:49:14.239Z",
    "source": "项目现有 2026 招生计划与 2023-2025 专业组最低分数据库",
    "sourceFiles": [
      "data-db-part-01.js",
      "data-db-part-02.js",
      "data-db-part-03.js",
      "data-db-part-04.js",
      "data-db-part-05.js",
      "data-db-part-06.js",
      "data-db-part-07.js",
      "data-db-part-08.js",
      "data-db-part-09.js",
      "data-db-part-10.js",
      "data-db-part-11.js",
      "data-db-part-12.js",
      "data-db-part-13.js"
    ],
    "sampleScore": 610,
    "subject": "物理",
    "batch": "本科批",
    "selectionRule": "至少两年可用专业组最低分；每个冲稳保区间各 12 组；同校最多 2 组",
    "totalSourceGroups": 9386,
    "previewGroups": 36
  },
  "groups": [
    {
      "id": "g_28c1b44e6ca9",
      "groupCode": "416203",
      "displayCode": "03",
      "groupName": "大连理工大学(盘锦校区)03",
      "school": "大连理工大学(盘锦校区)",
      "province": "辽宁",
      "city": "盘锦",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 15,
      "plan25": 18,
      "score25": 602,
      "score24": 628,
      "score23": 621,
      "rank25": 32191,
      "rank24": 12578,
      "rank23": 17908,
      "groupMajorCount": 5,
      "tags": [
        "985",
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师",
        "中外合作",
        "高收费"
      ],
      "majorSummary": "中外合作：数理基础科学、过程装备与控制工程、应用化学、药学等",
      "majorClasses": [
        "数学类",
        "机械类",
        "化学类",
        "药学类",
        "环境科学与工程类"
      ],
      "majors": [
        {
          "key": "m_416203_07",
          "code": "07",
          "name": "数理基础科学(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)",
          "baseName": "数理基础科学",
          "majorClass": "数学类",
          "discipline": "理学",
          "plan26": 3,
          "score25": 613,
          "rank25": 23215,
          "tuition": 85000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)"
        },
        {
          "key": "m_416203_08",
          "code": "08",
          "name": "过程装备与控制工程(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)",
          "baseName": "过程装备与控制工程",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 616,
          "rank25": 21044,
          "tuition": 85000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)"
        },
        {
          "key": "m_416203_09",
          "code": "09",
          "name": "应用化学(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)",
          "baseName": "应用化学",
          "majorClass": "化学类",
          "discipline": "理学",
          "plan26": 3,
          "score25": 619,
          "rank25": 19005,
          "tuition": 85000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)"
        },
        {
          "key": "m_416203_10",
          "code": "10",
          "name": "药学(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)",
          "baseName": "药学",
          "majorClass": "药学类",
          "discipline": "医学",
          "plan26": 3,
          "score25": 602,
          "rank25": 32191,
          "tuition": 85000,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)"
        },
        {
          "key": "m_416203_11",
          "code": "11",
          "name": "环境生态工程(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)",
          "baseName": "环境生态工程",
          "majorClass": "环境科学与工程类",
          "discipline": "工学",
          "plan26": 4,
          "score25": 602,
          "rank25": 32191,
          "tuition": 85000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业与英国莱斯特大学合作,部分课程采用英语授课)(中外合作办学)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "药学"
      ]
    },
    {
      "id": "g_71a33c73813d",
      "groupCode": "120119",
      "displayCode": "19",
      "groupName": "江南大学19",
      "school": "江南大学",
      "province": "江苏",
      "city": "无锡",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 160,
      "plan25": 155,
      "score25": 624,
      "score24": 617,
      "score23": 610,
      "rank25": 15714,
      "rank24": 18491,
      "rank23": 24841,
      "groupMajorCount": 4,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "自动化、计算机复合组",
      "majorClasses": [
        "自动化类",
        "计算机类",
        "电气类"
      ],
      "majors": [
        {
          "key": "m_120119_36",
          "code": "36",
          "name": "自动化(数字智能卓越创新班)(以下专业在蠡湖校区学习)",
          "baseName": "自动化",
          "majorClass": "自动化类",
          "discipline": "工学",
          "plan26": 9,
          "score25": 630,
          "rank25": 12321,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(数字智能卓越创新班)(以下专业在蠡湖校区学习)"
        },
        {
          "key": "m_120119_37",
          "code": "37",
          "name": "自动化(以下专业在蠡湖校区学习)",
          "baseName": "自动化",
          "majorClass": "自动化类",
          "discipline": "工学",
          "plan26": 52,
          "score25": 626,
          "rank25": 14488,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在蠡湖校区学习)"
        },
        {
          "key": "m_120119_38",
          "code": "38",
          "name": "物联网工程(以下专业在蠡湖校区学习)",
          "baseName": "物联网工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 61,
          "score25": 624,
          "rank25": 15714,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在蠡湖校区学习)"
        },
        {
          "key": "m_120119_39",
          "code": "39",
          "name": "电气工程及其自动化(以下专业在蠡湖校区学习)",
          "baseName": "电气工程及其自动化",
          "majorClass": "电气类",
          "discipline": "工学",
          "plan26": 38,
          "score25": 625,
          "rank25": 15100,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在蠡湖校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_c64f9d431fad",
      "groupCode": "313303",
      "displayCode": "03",
      "groupName": "首都师范大学03",
      "school": "首都师范大学",
      "province": "北京",
      "city": "海淀区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 2,
      "plan25": 2,
      "score25": 625,
      "score24": 610,
      "score23": 615,
      "rank25": 15100,
      "rank24": 22843,
      "rank23": 21590,
      "groupMajorCount": 1,
      "tags": [
        "双一流",
        "保研资格"
      ],
      "majorSummary": "数学物理组",
      "majorClasses": [
        "数学类"
      ],
      "majors": [
        {
          "key": "m_313303_11",
          "code": "11",
          "name": "数学与应用数学(教育部拔尖计划实验班)",
          "baseName": "数学与应用数学",
          "majorClass": "数学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 625,
          "rank25": 15100,
          "tuition": 5000,
          "duration": "4",
          "risk": false,
          "remark": "(教育部拔尖计划实验班)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_f86048f00ac5",
      "groupCode": "420120",
      "displayCode": "20",
      "groupName": "吉林大学20",
      "school": "吉林大学",
      "province": "吉林",
      "city": "长春",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 5,
      "plan25": 10,
      "score25": 626,
      "score24": 634,
      "score23": 594,
      "rank25": 14488,
      "rank24": 9941,
      "rank23": 36407,
      "groupMajorCount": 2,
      "tags": [
        "985",
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "数学物理、机械土木复合组",
      "majorClasses": [
        "地质类",
        "土木类"
      ],
      "majors": [
        {
          "key": "m_420120_62",
          "code": "62",
          "name": "勘查技术与工程(按大类招生)(含勘查技术与工程、地球物理学、地理信息科学、测绘工程)(前卫南区)(类内专业分流任选)(100%按照学生意愿分流)",
          "baseName": "勘查技术与工程",
          "majorClass": "地质类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 628,
          "rank25": 13360,
          "tuition": 6320,
          "duration": "4",
          "risk": false,
          "remark": "(按大类招生)(含勘查技术与工程、地球物理学、地理信息科学、测绘工程)(前卫南区)(类内专业分流任选)(100%按照学生意愿分流)"
        },
        {
          "key": "m_420120_63",
          "code": "63",
          "name": "土木类(土木工程、地质工程)(前卫南区)(类内专业分流任选)(100%按照学生意愿分流)",
          "baseName": "土木类",
          "majorClass": "土木类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 626,
          "rank25": 14488,
          "tuition": 6830,
          "duration": "4",
          "risk": true,
          "remark": "(土木工程、地质工程)(前卫南区)(类内专业分流任选)(100%按照学生意愿分流)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "土木类"
      ]
    },
    {
      "id": "g_c52ac5b2da67",
      "groupCode": "510103",
      "displayCode": "03",
      "groupName": "郑州大学03",
      "school": "郑州大学",
      "province": "河南",
      "city": "郑州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 17,
      "plan25": 12,
      "score25": 615,
      "score24": 612,
      "score23": 612,
      "rank25": 21736,
      "rank24": 21589,
      "rank23": 23568,
      "groupMajorCount": 4,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "计算机、电子信息、自动化复合组",
      "majorClasses": [
        "电子信息类",
        "计算机类",
        "电气类"
      ],
      "majors": [
        {
          "key": "m_510103_05",
          "code": "05",
          "name": "电子信息工程(以下专业在主校区学习)",
          "baseName": "电子信息工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 617,
          "rank25": 20350,
          "tuition": 5700,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在主校区学习)"
        },
        {
          "key": "m_510103_06",
          "code": "06",
          "name": "计算机科学与技术(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在主校区学习)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 5,
          "score25": 619,
          "rank25": 19005,
          "tuition": 5700,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在主校区学习)"
        },
        {
          "key": "m_510103_07",
          "code": "07",
          "name": "人工智能(以下专业在主校区学习)",
          "baseName": "人工智能",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 4,
          "score25": 615,
          "rank25": 21736,
          "tuition": 5700,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在主校区学习)"
        },
        {
          "key": "m_510103_08",
          "code": "08",
          "name": "电气工程及其自动化(以下专业在主校区学习)",
          "baseName": "电气工程及其自动化",
          "majorClass": "电气类",
          "discipline": "工学",
          "plan26": 5,
          "score25": null,
          "rank25": null,
          "tuition": 5700,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在主校区学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "计算机科学与技术"
      ]
    },
    {
      "id": "g_91c15d101e28",
      "groupCode": "545103",
      "displayCode": "03",
      "groupName": "深圳大学03",
      "school": "深圳大学",
      "province": "广东",
      "city": "深圳",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 2,
      "plan25": 2,
      "score25": 611,
      "score24": 611,
      "score23": null,
      "rank25": 24770,
      "rank24": 22222,
      "rank23": null,
      "groupMajorCount": 1,
      "tags": [
        "保研资格",
        "中外合作",
        "高收费"
      ],
      "majorSummary": "中外合作：金融科技",
      "majorClasses": [
        "金融学类"
      ],
      "majors": [
        {
          "key": "m_545103_07",
          "code": "07",
          "name": "金融科技(粤海校区)(以下专业具体出国培养模式、学费等要求,须查阅院校招生章程并详询院校)(中外合作办学)",
          "baseName": "金融科技",
          "majorClass": "金融学类",
          "discipline": "经济学",
          "plan26": 2,
          "score25": 611,
          "rank25": 24770,
          "tuition": 81500,
          "duration": "4",
          "risk": false,
          "remark": "(粤海校区)(以下专业具体出国培养模式、学费等要求,须查阅院校招生章程并详询院校)(中外合作办学)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_88db3c2259a8",
      "groupCode": "230304",
      "displayCode": "04",
      "groupName": "安徽大学04",
      "school": "安徽大学",
      "province": "安徽",
      "city": "合肥",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 29,
      "plan25": 20,
      "score25": 614,
      "score24": 613,
      "score23": 614,
      "rank25": 22496,
      "rank24": 20991,
      "rank23": 22200,
      "groupMajorCount": 11,
      "tags": [
        "211",
        "双一流",
        "保研资格"
      ],
      "majorSummary": "电子信息、计算机、自动化复合组",
      "majorClasses": [
        "物理学类",
        "电子信息类",
        "材料类",
        "计算机类",
        "交叉学科类",
        "自动化类",
        "机械类",
        "测绘类"
      ],
      "majors": [
        {
          "key": "m_230304_20",
          "code": "20",
          "name": "应用物理学(磬苑校区)(以下专业除注明外在龙河校区学习)",
          "baseName": "应用物理学",
          "majorClass": "物理学类",
          "discipline": "理学",
          "plan26": 3,
          "score25": null,
          "rank25": null,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(磬苑校区)(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_21",
          "code": "21",
          "name": "光电信息科学与工程(金寨路校区)(以下专业除注明外在龙河校区学习)",
          "baseName": "光电信息科学与工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 615,
          "rank25": 21736,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(金寨路校区)(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_22",
          "code": "22",
          "name": "新能源材料与器件(金寨路校区)(以下专业除注明外在龙河校区学习)",
          "baseName": "新能源材料与器件",
          "majorClass": "材料类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6480,
          "duration": "4",
          "risk": true,
          "remark": "(金寨路校区)(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_23",
          "code": "23",
          "name": "计算机科学与技术(以下专业除注明外在龙河校区学习)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 622,
          "rank25": 17029,
          "tuition": 6480,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_24",
          "code": "24",
          "name": "电子信息工程(以下专业除注明外在龙河校区学习)",
          "baseName": "电子信息工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 620,
          "rank25": 18320,
          "tuition": 6480,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_25",
          "code": "25",
          "name": "低空技术与工程(以下专业除注明外在龙河校区学习)",
          "baseName": "低空技术与工程",
          "majorClass": "交叉学科类",
          "discipline": "交叉学科",
          "plan26": 4,
          "score25": null,
          "rank25": null,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_26",
          "code": "26",
          "name": "自动化(以下专业除注明外在龙河校区学习)",
          "baseName": "自动化",
          "majorClass": "自动化类",
          "discipline": "工学",
          "plan26": 4,
          "score25": 618,
          "rank25": 19675,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_27",
          "code": "27",
          "name": "新能源汽车工程(以下专业除注明外在龙河校区学习)",
          "baseName": "新能源汽车工程",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 618,
          "rank25": 19675,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_28",
          "code": "28",
          "name": "机械设计制造及其自动化(以下专业除注明外在龙河校区学习)",
          "baseName": "机械设计制造及其自动化",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 616,
          "rank25": 21044,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_29",
          "code": "29",
          "name": "数据科学与大数据技术(金寨路校区)(以下专业除注明外在龙河校区学习)",
          "baseName": "数据科学与大数据技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 617,
          "rank25": 20350,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(金寨路校区)(以下专业除注明外在龙河校区学习)"
        },
        {
          "key": "m_230304_30",
          "code": "30",
          "name": "测绘工程(金寨路校区)(以下专业除注明外在龙河校区学习)",
          "baseName": "测绘工程",
          "majorClass": "测绘类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5400,
          "duration": "4",
          "risk": false,
          "remark": "(金寨路校区)(以下专业除注明外在龙河校区学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "新能源材料与器件"
      ]
    },
    {
      "id": "g_015fc0cb714b",
      "groupCode": "120120",
      "displayCode": "20",
      "groupName": "江南大学20",
      "school": "江南大学",
      "province": "江苏",
      "city": "无锡",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 49,
      "plan25": 40,
      "score25": 623,
      "score24": 616,
      "score23": 607,
      "rank25": 16380,
      "rank24": 19076,
      "rank23": 26858,
      "groupMajorCount": 2,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "电子信息组",
      "majorClasses": [
        "电子信息类"
      ],
      "majors": [
        {
          "key": "m_120120_40",
          "code": "40",
          "name": "微电子科学与工程(以下专业在江阴校区学习)",
          "baseName": "微电子科学与工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 35,
          "score25": 624,
          "rank25": 15714,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在江阴校区学习)"
        },
        {
          "key": "m_120120_41",
          "code": "41",
          "name": "电子封装技术(以下专业在江阴校区学习)",
          "baseName": "电子封装技术",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 14,
          "score25": 623,
          "rank25": 16380,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在江阴校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_61c567f5a8b6",
      "groupCode": "126154",
      "displayCode": "54",
      "groupName": "苏州大学54",
      "school": "苏州大学",
      "province": "江苏",
      "city": "苏州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 114,
      "plan25": 101,
      "score25": 614,
      "score24": 613,
      "score23": 614,
      "rank25": 22496,
      "rank24": 20991,
      "rank23": 22200,
      "groupMajorCount": 2,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "生物食品环境组",
      "majorClasses": [
        "生物工程类",
        "药学类"
      ],
      "majors": [
        {
          "key": "m_126154_D1",
          "code": "D1",
          "name": "生物制药(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "生物制药",
          "majorClass": "生物工程类",
          "discipline": "工学",
          "plan26": 29,
          "score25": 618,
          "rank25": 19675,
          "tuition": 6380,
          "duration": "4",
          "risk": true,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_126154_D2",
          "code": "D2",
          "name": "药学(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "药学",
          "majorClass": "药学类",
          "discipline": "医学",
          "plan26": 85,
          "score25": 614,
          "rank25": 22496,
          "tuition": 7480,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "生物制药",
        "药学"
      ]
    },
    {
      "id": "g_c3865cba79a3",
      "groupCode": "122311",
      "displayCode": "11",
      "groupName": "徐州医科大学11",
      "school": "徐州医科大学",
      "province": "江苏",
      "city": "徐州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 50,
      "plan25": 50,
      "score25": 627,
      "score24": 630,
      "score23": 589,
      "rank25": 13916,
      "rank24": 11630,
      "rank23": 40322,
      "groupMajorCount": 2,
      "tags": [
        "保研资格",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "临床医学类"
      ],
      "majors": [
        {
          "key": "m_122311_41",
          "code": "41",
          "name": "麻醉学(卓越班)(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "麻醉学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 30,
          "score25": 632,
          "rank25": 11249,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(卓越班)(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_122311_42",
          "code": "42",
          "name": "临床医学(卓越班)(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 20,
          "score25": 627,
          "rank25": 13916,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(卓越班)(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "麻醉学",
        "临床医学"
      ]
    },
    {
      "id": "g_4d6bec8e3dc5",
      "groupCode": "314809",
      "displayCode": "09",
      "groupName": "北京电影学院09",
      "school": "北京电影学院",
      "province": "北京",
      "city": "海淀区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 1,
      "plan25": 1,
      "score25": 626,
      "score24": 609,
      "score23": null,
      "rank25": 14488,
      "rank24": 23502,
      "rank23": null,
      "groupMajorCount": 1,
      "tags": [
        "保研资格"
      ],
      "majorSummary": "艺术体育组",
      "majorClasses": [
        "戏剧与影视学类"
      ],
      "majors": [
        {
          "key": "m_314809_09",
          "code": "09",
          "name": "戏剧影视文学(报考该专业须查阅院校招生章程)",
          "baseName": "戏剧影视文学",
          "majorClass": "戏剧与影视学类",
          "discipline": "艺术学",
          "plan26": 1,
          "score25": 626,
          "rank25": 14488,
          "tuition": 8000,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业须查阅院校招生章程)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_8e32bbcd547f",
      "groupCode": "611102",
      "displayCode": "02",
      "groupName": "成都中医药大学02",
      "school": "成都中医药大学",
      "province": "四川",
      "city": "成都",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 4,
      "plan25": 4,
      "score25": 614,
      "score24": 614,
      "score23": 614,
      "rank25": 22496,
      "rank24": 20315,
      "rank23": 22200,
      "groupMajorCount": 2,
      "tags": [
        "双一流",
        "保研资格",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "中医学类"
      ],
      "majors": [
        {
          "key": "m_611102_03",
          "code": "03",
          "name": "中医学(李斯炽班)(九年制)(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 624,
          "rank25": 15714,
          "tuition": 6960,
          "duration": "9",
          "risk": false,
          "remark": "(李斯炽班)(九年制)(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_611102_04",
          "code": "04",
          "name": "中医学(5+3一体化)(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6960,
          "duration": "5",
          "risk": false,
          "remark": "(5+3一体化)(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "中医学",
        "中医学"
      ]
    },
    {
      "id": "g_2009906e95f3",
      "groupCode": "413209",
      "displayCode": "09",
      "groupName": "大连海事大学09",
      "school": "大连海事大学",
      "province": "辽宁",
      "city": "大连",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 57,
      "plan25": 51,
      "score25": 612,
      "score24": 608,
      "score23": 606,
      "rank25": 23948,
      "rank24": 24206,
      "rank23": 27545,
      "groupMajorCount": 9,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "计算机、自动化、机械土木复合组",
      "majorClasses": [
        "自动化类",
        "电子信息类",
        "计算机类",
        "交通运输类",
        "机械类",
        "地理科学类"
      ],
      "majors": [
        {
          "key": "m_413209_23",
          "code": "23",
          "name": "自动化类(自动化、电气工程及其自动化、测控技术与仪器)(以下专业在校本部学习)",
          "baseName": "自动化类",
          "majorClass": "自动化类",
          "discipline": "工学",
          "plan26": 8,
          "score25": 615,
          "rank25": 21736,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(自动化、电气工程及其自动化、测控技术与仪器)(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_24",
          "code": "24",
          "name": "电子信息类(电子信息工程、电子信息科学与技术、通信工程、光电信息科学与工程)(以下专业在校本部学习)",
          "baseName": "电子信息类",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 13,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5980,
          "duration": "4",
          "risk": false,
          "remark": "(电子信息工程、电子信息科学与技术、通信工程、光电信息科学与工程)(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_25",
          "code": "25",
          "name": "计算机类(计算机科学与技术、软件工程、数据科学与大数据技术、网络工程、智能科学与技术)(以下专业在校本部学习)",
          "baseName": "计算机类",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 14,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(计算机科学与技术、软件工程、数据科学与大数据技术、网络工程、智能科学与技术)(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_26",
          "code": "26",
          "name": "交通运输类(交通运输、物流工程、材料科学与工程、交通工程)(以下专业在校本部学习)",
          "baseName": "交通运输类",
          "majorClass": "交通运输类",
          "discipline": "工学",
          "plan26": 6,
          "score25": 612,
          "rank25": 23948,
          "tuition": 5980,
          "duration": "4",
          "risk": true,
          "remark": "(交通运输、物流工程、材料科学与工程、交通工程)(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_27",
          "code": "27",
          "name": "机械类(机械设计制造及其自动化、船舶与海洋工程、能源与动力工程、救助与打捞工程(海洋智能装备))(以下专业在校本部学习)",
          "baseName": "机械类",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 4,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(机械设计制造及其自动化、船舶与海洋工程、能源与动力工程、救助与打捞工程(海洋智能装备))(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_28",
          "code": "28",
          "name": "地理信息科学(以下专业在校本部学习)",
          "baseName": "地理信息科学",
          "majorClass": "地理科学类",
          "discipline": "理学",
          "plan26": 3,
          "score25": null,
          "rank25": null,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_29",
          "code": "29",
          "name": "轮机工程(陆上专业)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在校本部学习)",
          "baseName": "轮机工程",
          "majorClass": "交通运输类",
          "discipline": "工学",
          "plan26": 3,
          "score25": null,
          "rank25": null,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(陆上专业)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_30",
          "code": "30",
          "name": "物联网工程(以下专业在校本部学习)",
          "baseName": "物联网工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在校本部学习)"
        },
        {
          "key": "m_413209_31",
          "code": "31",
          "name": "人工智能(以下专业在校本部学习)",
          "baseName": "人工智能",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5200,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在校本部学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "交通运输类",
        "轮机工程"
      ]
    },
    {
      "id": "g_1db951d8e36e",
      "groupCode": "420210",
      "displayCode": "10",
      "groupName": "东北师范大学10",
      "school": "东北师范大学",
      "province": "吉林",
      "city": "长春",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 12,
      "plan25": 3,
      "score25": 615,
      "score24": 610,
      "score23": 602,
      "rank25": 21736,
      "rank24": 22843,
      "rank23": 30377,
      "groupMajorCount": 3,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "师范"
      ],
      "majorSummary": "计算机、电子信息复合组",
      "majorClasses": [
        "统计学类",
        "计算机类",
        "物理学类"
      ],
      "majors": [
        {
          "key": "m_420210_10",
          "code": "10",
          "name": "数据科学(人民大街校区)",
          "baseName": "数据科学",
          "majorClass": "统计学类",
          "discipline": "理学",
          "plan26": 4,
          "score25": null,
          "rank25": null,
          "tuition": 5750,
          "duration": "4",
          "risk": false,
          "remark": "(人民大街校区)"
        },
        {
          "key": "m_420210_11",
          "code": "11",
          "name": "计算机类(计算机科学与技术、数据科学与大数据技术、人工智能、教育技术学(智能教育,师范)、人工智能教育(师范))(净月大街校区)",
          "baseName": "计算机类",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 5,
          "score25": null,
          "rank25": null,
          "tuition": 5520,
          "duration": "4",
          "risk": false,
          "remark": "(计算机科学与技术、数据科学与大数据技术、人工智能、教育技术学(智能教育,师范)、人工智能教育(师范))(净月大街校区)"
        },
        {
          "key": "m_420210_12",
          "code": "12",
          "name": "物理学类(物理学(师范)、电子信息科学与技术、材料物理)(人民大街校区)",
          "baseName": "物理学类",
          "majorClass": "物理学类",
          "discipline": "理学",
          "plan26": 3,
          "score25": 615,
          "rank25": 21736,
          "tuition": 6320,
          "duration": "4",
          "risk": true,
          "remark": "(物理学(师范)、电子信息科学与技术、材料物理)(人民大街校区)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "物理学类"
      ]
    },
    {
      "id": "g_b37323fba8f6",
      "groupCode": "110405",
      "displayCode": "05",
      "groupName": "南京理工大学05",
      "school": "南京理工大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 50,
      "plan25": 70,
      "score25": 616,
      "score24": 607,
      "score23": 601,
      "rank25": 21044,
      "rank24": 24905,
      "rank23": 31135,
      "groupMajorCount": 2,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师",
        "中外合作",
        "高收费"
      ],
      "majorSummary": "中外合作：机械工程、材料科学与工程",
      "majorClasses": [
        "机械类",
        "材料类"
      ],
      "majors": [
        {
          "key": "m_110405_49",
          "code": "49",
          "name": "机械工程(以下专业与法国梅斯国立工程师学院合作办学,四年均在江阴校区学习)(中外合作办学)",
          "baseName": "机械工程",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 26,
          "score25": 619,
          "rank25": 19005,
          "tuition": 57000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业与法国梅斯国立工程师学院合作办学,四年均在江阴校区学习)(中外合作办学)"
        },
        {
          "key": "m_110405_50",
          "code": "50",
          "name": "材料科学与工程(以下专业与法国梅斯国立工程师学院合作办学,四年均在江阴校区学习)(中外合作办学)",
          "baseName": "材料科学与工程",
          "majorClass": "材料类",
          "discipline": "工学",
          "plan26": 24,
          "score25": 616,
          "rank25": 21044,
          "tuition": 57000,
          "duration": "4",
          "risk": true,
          "remark": "(以下专业与法国梅斯国立工程师学院合作办学,四年均在江阴校区学习)(中外合作办学)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "材料科学与工程"
      ]
    },
    {
      "id": "g_d709e31bdc8c",
      "groupCode": "110709",
      "displayCode": "09",
      "groupName": "南京农业大学09",
      "school": "南京农业大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 321,
      "plan25": 293,
      "score25": 612,
      "score24": 607,
      "score23": 608,
      "rank25": 23948,
      "rank24": 24905,
      "rank23": 26161,
      "groupMajorCount": 11,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格"
      ],
      "majorSummary": "数学物理、自动化、计算机复合组",
      "majorClasses": [
        "数学类",
        "化学类",
        "统计学类",
        "机械类",
        "农业工程类",
        "能源动力类",
        "电子信息类",
        "计算机类"
      ],
      "majors": [
        {
          "key": "m_110709_40",
          "code": "40",
          "name": "信息与计算科学",
          "baseName": "信息与计算科学",
          "majorClass": "数学类",
          "discipline": "理学",
          "plan26": 24,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5500,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_41",
          "code": "41",
          "name": "应用化学(报考该专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "应用化学",
          "majorClass": "化学类",
          "discipline": "理学",
          "plan26": 4,
          "score25": 612,
          "rank25": 23948,
          "tuition": 5500,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_110709_42",
          "code": "42",
          "name": "统计学",
          "baseName": "统计学",
          "majorClass": "统计学类",
          "discipline": "理学",
          "plan26": 4,
          "score25": 612,
          "rank25": 23948,
          "tuition": 5500,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_43",
          "code": "43",
          "name": "机械类(车辆工程、机械工程)",
          "baseName": "机械类",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 49,
          "score25": 612,
          "rank25": 23948,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(车辆工程、机械工程)"
        },
        {
          "key": "m_110709_44",
          "code": "44",
          "name": "农业机械化及其自动化",
          "baseName": "农业机械化及其自动化",
          "majorClass": "农业工程类",
          "discipline": "工学",
          "plan26": 20,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_45",
          "code": "45",
          "name": "农业电气化",
          "baseName": "农业电气化",
          "majorClass": "农业工程类",
          "discipline": "工学",
          "plan26": 18,
          "score25": 613,
          "rank25": 23215,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_46",
          "code": "46",
          "name": "农业智能装备工程",
          "baseName": "农业智能装备工程",
          "majorClass": "农业工程类",
          "discipline": "工学",
          "plan26": 10,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_47",
          "code": "47",
          "name": "新能源科学与工程",
          "baseName": "新能源科学与工程",
          "majorClass": "能源动力类",
          "discipline": "工学",
          "plan26": 20,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_48",
          "code": "48",
          "name": "电子信息类(电子信息科学与技术、自动化)",
          "baseName": "电子信息类",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 95,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(电子信息科学与技术、自动化)"
        },
        {
          "key": "m_110709_49",
          "code": "49",
          "name": "人工智能",
          "baseName": "人工智能",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 37,
          "score25": 615,
          "rank25": 21736,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110709_50",
          "code": "50",
          "name": "计算机科学与技术(报考该专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 40,
          "score25": 617,
          "rank25": 20350,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "应用化学",
        "计算机科学与技术"
      ]
    },
    {
      "id": "g_76d370508ed0",
      "groupCode": "111107",
      "displayCode": "07",
      "groupName": "南京邮电大学07",
      "school": "南京邮电大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 974,
      "plan25": 833,
      "score25": 610,
      "score24": 604,
      "score23": 613,
      "rank25": 25516,
      "rank24": 27035,
      "rank23": 22857,
      "groupMajorCount": 10,
      "tags": [
        "双一流",
        "保研资格",
        "卓越工程师",
        "双学位"
      ],
      "majorSummary": "电子信息组",
      "majorClasses": [
        "电子信息类",
        "交叉学科类",
        "物理学类"
      ],
      "majors": [
        {
          "key": "m_111107_30",
          "code": "30",
          "name": "电子科学与技术(拔尖创新班)(以下专业在仙林校区学习)",
          "baseName": "电子科学与技术",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 30,
          "score25": null,
          "rank25": null,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(拔尖创新班)(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_31",
          "code": "31",
          "name": "电子科学与技术(以下专业在仙林校区学习)",
          "baseName": "电子科学与技术",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 277,
          "score25": 618,
          "rank25": 19675,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_32",
          "code": "32",
          "name": "集成电路设计与集成系统(EDA菁英班)(以下专业在仙林校区学习)",
          "baseName": "集成电路设计与集成系统",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 30,
          "score25": null,
          "rank25": null,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(EDA菁英班)(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_33",
          "code": "33",
          "name": "集成电路设计与集成系统(以下专业在仙林校区学习)",
          "baseName": "集成电路设计与集成系统",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 136,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_34",
          "code": "34",
          "name": "微电子科学与工程(以下专业在仙林校区学习)",
          "baseName": "微电子科学与工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 168,
          "score25": 615,
          "rank25": 21736,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_35",
          "code": "35",
          "name": "集成电路科学与工程(以下专业在仙林校区学习)",
          "baseName": "集成电路科学与工程",
          "majorClass": "交叉学科类",
          "discipline": "交叉学科",
          "plan26": 87,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_36",
          "code": "36",
          "name": "光电信息科学与工程(以下专业在仙林校区学习)",
          "baseName": "光电信息科学与工程",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 95,
          "score25": 611,
          "rank25": 24770,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_37",
          "code": "37",
          "name": "柔性电子学(以下专业在仙林校区学习)",
          "baseName": "柔性电子学",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 48,
          "score25": 611,
          "rank25": 24770,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_38",
          "code": "38",
          "name": "电磁场与无线技术(以下专业在仙林校区学习)",
          "baseName": "电磁场与无线技术",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 54,
          "score25": 610,
          "rank25": 25516,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111107_39",
          "code": "39",
          "name": "应用物理学(应用物理学+电子科学与技术双学士学位复合型人才培养项目)(以下专业在仙林校区学习)",
          "baseName": "应用物理学",
          "majorClass": "物理学类",
          "discipline": "理学",
          "plan26": 49,
          "score25": 610,
          "rank25": 25516,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(应用物理学+电子科学与技术双学士学位复合型人才培养项目)(以下专业在仙林校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_041a5a7a012c",
      "groupCode": "111108",
      "displayCode": "08",
      "groupName": "南京邮电大学08",
      "school": "南京邮电大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 798,
      "plan25": 764,
      "score25": 610,
      "score24": 604,
      "score23": 613,
      "rank25": 25516,
      "rank24": 27035,
      "rank23": 22857,
      "groupMajorCount": 9,
      "tags": [
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "计算机、数学物理复合组",
      "majorClasses": [
        "计算机类",
        "数学类"
      ],
      "majors": [
        {
          "key": "m_111108_40",
          "code": "40",
          "name": "计算机科学与技术(拔尖创新班)(以下专业在仙林校区学习)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 30,
          "score25": null,
          "rank25": null,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(拔尖创新班)(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_41",
          "code": "41",
          "name": "计算机科学与技术(以下专业在仙林校区学习)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 216,
          "score25": 618,
          "rank25": 19675,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_42",
          "code": "42",
          "name": "信息安全(以下专业在仙林校区学习)",
          "baseName": "信息安全",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 206,
          "score25": 613,
          "rank25": 23215,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_43",
          "code": "43",
          "name": "软件工程(以下专业在仙林校区学习)",
          "baseName": "软件工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 115,
          "score25": 615,
          "rank25": 21736,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_44",
          "code": "44",
          "name": "数据科学与大数据技术(以下专业在仙林校区学习)",
          "baseName": "数据科学与大数据技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 80,
          "score25": 611,
          "rank25": 24770,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_45",
          "code": "45",
          "name": "物联网工程(鸿蒙菁英班)(以下专业在仙林校区学习)",
          "baseName": "物联网工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 30,
          "score25": null,
          "rank25": null,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(鸿蒙菁英班)(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_46",
          "code": "46",
          "name": "物联网工程(以下专业在仙林校区学习)",
          "baseName": "物联网工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 58,
          "score25": 610,
          "rank25": 25516,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_47",
          "code": "47",
          "name": "网络工程(以下专业在仙林校区学习)",
          "baseName": "网络工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 33,
          "score25": 610,
          "rank25": 25516,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在仙林校区学习)"
        },
        {
          "key": "m_111108_48",
          "code": "48",
          "name": "信息与计算科学(省拔尖学生培养基地)(以下专业在仙林校区学习)",
          "baseName": "信息与计算科学",
          "majorClass": "数学类",
          "discipline": "理学",
          "plan26": 30,
          "score25": 611,
          "rank25": 24770,
          "tuition": 6050,
          "duration": "4",
          "risk": false,
          "remark": "(省拔尖学生培养基地)(以下专业在仙林校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_b7685652ff49",
      "groupCode": "211205",
      "displayCode": "05",
      "groupName": "上海大学05",
      "school": "上海大学",
      "province": "上海",
      "city": "宝山区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 17,
      "plan25": 17,
      "score25": 607,
      "score24": 606,
      "score23": 613,
      "rank25": 27966,
      "rank24": 25606,
      "rank23": 22857,
      "groupMajorCount": 3,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师",
        "中外合作",
        "高收费"
      ],
      "majorSummary": "中外合作：国际经济与贸易、信息管理与信息系统、金融学",
      "majorClasses": [
        "经济与贸易类",
        "管理科学与工程类",
        "金融学类"
      ],
      "majors": [
        {
          "key": "m_211205_08",
          "code": "08",
          "name": "国际经济与贸易(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)",
          "baseName": "国际经济与贸易",
          "majorClass": "经济与贸易类",
          "discipline": "经济学",
          "plan26": 4,
          "score25": 608,
          "rank25": 27151,
          "tuition": 40000,
          "duration": "4",
          "risk": false,
          "remark": "(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)"
        },
        {
          "key": "m_211205_09",
          "code": "09",
          "name": "信息管理与信息系统(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)",
          "baseName": "信息管理与信息系统",
          "majorClass": "管理科学与工程类",
          "discipline": "管理学",
          "plan26": 10,
          "score25": 607,
          "rank25": 27966,
          "tuition": 40000,
          "duration": "4",
          "risk": false,
          "remark": "(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)"
        },
        {
          "key": "m_211205_10",
          "code": "10",
          "name": "金融学(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)",
          "baseName": "金融学",
          "majorClass": "金融学类",
          "discipline": "经济学",
          "plan26": 3,
          "score25": 614,
          "rank25": 22496,
          "tuition": 40000,
          "duration": "4",
          "risk": false,
          "remark": "(中澳合作)(以下专业在嘉定校区学习)(中外合作办学)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_d8bc5524bea2",
      "groupCode": "224103",
      "displayCode": "03",
      "groupName": "温州医科大学03",
      "school": "温州医科大学",
      "province": "浙江",
      "city": "温州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 5,
      "plan25": 5,
      "score25": 604,
      "score24": 602,
      "score23": 621,
      "rank25": 30493,
      "rank24": 28486,
      "rank23": 17908,
      "groupMajorCount": 1,
      "tags": [
        "保研资格",
        "中外合作",
        "医学",
        "高收费"
      ],
      "majorSummary": "中外合作：临床医学",
      "majorClasses": [
        "临床医学类"
      ],
      "majors": [
        {
          "key": "m_224103_09",
          "code": "09",
          "name": "临床医学(茶山校区)(该校要求报考该专业外语成绩不低于120分,报考该专业有色觉要求,具体出国培养模式、学费等要求,须查阅院校招生章程并详询院校)(中外合作办学)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 5,
          "score25": 604,
          "rank25": 30493,
          "tuition": 75000,
          "duration": "5",
          "risk": false,
          "remark": "(茶山校区)(该校要求报考该专业外语成绩不低于120分,报考该专业有色觉要求,具体出国培养模式、学费等要求,须查阅院校招生章程并详询院校)(中外合作办学)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "临床医学"
      ]
    },
    {
      "id": "g_59f0f0101cd6",
      "groupCode": "620221",
      "displayCode": "21",
      "groupName": "西南大学21",
      "school": "西南大学",
      "province": "重庆",
      "city": "北碚区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "地理",
      "plan26": 1,
      "plan25": 1,
      "score25": 612,
      "score24": 608,
      "score23": 607,
      "rank25": 23948,
      "rank24": 24206,
      "rank23": 26858,
      "groupMajorCount": 1,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格"
      ],
      "majorSummary": "地理建筑组",
      "majorClasses": [
        "地理科学类"
      ],
      "majors": [
        {
          "key": "m_620221_56",
          "code": "56",
          "name": "地理科学类(地理信息科学、人文地理与城乡规划)",
          "baseName": "地理科学类",
          "majorClass": "地理科学类",
          "discipline": "理学",
          "plan26": 1,
          "score25": 612,
          "rank25": 23948,
          "tuition": 6000,
          "duration": "4",
          "risk": false,
          "remark": "(地理信息科学、人文地理与城乡规划)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_f75a4e92cf39",
      "groupCode": "610214",
      "displayCode": "14",
      "groupName": "西南交通大学14",
      "school": "西南交通大学",
      "province": "四川",
      "city": "成都",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 20,
      "plan25": 10,
      "score25": 614,
      "score24": 605,
      "score23": 608,
      "rank25": 22496,
      "rank24": 26288,
      "rank23": 26161,
      "groupMajorCount": 6,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师",
        "双学位"
      ],
      "majorSummary": "计算机、自动化、电子信息复合组",
      "majorClasses": [
        "自动化类",
        "计算机类",
        "土木类",
        "建筑类",
        "交叉学科类"
      ],
      "majors": [
        {
          "key": "m_610214_51",
          "code": "51",
          "name": "机器人工程(以下专业在犀浦校区学习)",
          "baseName": "机器人工程",
          "majorClass": "自动化类",
          "discipline": "工学",
          "plan26": 3,
          "score25": null,
          "rank25": null,
          "tuition": 6240,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在犀浦校区学习)"
        },
        {
          "key": "m_610214_52",
          "code": "52",
          "name": "信息安全(以下专业在犀浦校区学习)",
          "baseName": "信息安全",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 4,
          "score25": 626,
          "rank25": 14488,
          "tuition": 6240,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在犀浦校区学习)"
        },
        {
          "key": "m_610214_53",
          "code": "53",
          "name": "土木工程(土木工程+数据科学与大数据技术双学士学位)(以下专业在犀浦校区学习)",
          "baseName": "土木工程",
          "majorClass": "土木类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6240,
          "duration": "4",
          "risk": true,
          "remark": "(土木工程+数据科学与大数据技术双学士学位)(以下专业在犀浦校区学习)"
        },
        {
          "key": "m_610214_54",
          "code": "54",
          "name": "建筑学(建筑学+数据科学与大数据技术双学士学位)(以下专业在犀浦校区学习)",
          "baseName": "建筑学",
          "majorClass": "建筑类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 619,
          "rank25": 19005,
          "tuition": 6240,
          "duration": "5",
          "risk": false,
          "remark": "(建筑学+数据科学与大数据技术双学士学位)(以下专业在犀浦校区学习)"
        },
        {
          "key": "m_610214_55",
          "code": "55",
          "name": "低空技术与工程(以下专业在犀浦校区学习)",
          "baseName": "低空技术与工程",
          "majorClass": "交叉学科类",
          "discipline": "交叉学科",
          "plan26": 3,
          "score25": null,
          "rank25": null,
          "tuition": 6240,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在犀浦校区学习)"
        },
        {
          "key": "m_610214_56",
          "code": "56",
          "name": "集成电路科学与工程(以下专业在犀浦校区学习)",
          "baseName": "集成电路科学与工程",
          "majorClass": "交叉学科类",
          "discipline": "交叉学科",
          "plan26": 4,
          "score25": null,
          "rank25": null,
          "tuition": 6240,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业在犀浦校区学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "土木工程"
      ]
    },
    {
      "id": "g_891061a71301",
      "groupCode": "510104",
      "displayCode": "04",
      "groupName": "郑州大学04",
      "school": "郑州大学",
      "province": "河南",
      "city": "郑州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 4,
      "plan25": 4,
      "score25": 608,
      "score24": 611,
      "score23": 607,
      "rank25": 27151,
      "rank24": 22222,
      "rank23": 26858,
      "groupMajorCount": 2,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "口腔医学类",
        "临床医学类"
      ],
      "majors": [
        {
          "key": "m_510104_09",
          "code": "09",
          "name": "口腔医学(主校区)(报考该专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "口腔医学",
          "majorClass": "口腔医学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 608,
          "rank25": 27151,
          "tuition": 6300,
          "duration": "5",
          "risk": false,
          "remark": "(主校区)(报考该专业有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_510104_10",
          "code": "10",
          "name": "临床医学(第二临床学院)(主校区)(报考该专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 616,
          "rank25": 21044,
          "tuition": 6300,
          "duration": "5",
          "risk": false,
          "remark": "(第二临床学院)(主校区)(报考该专业有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "口腔医学",
        "临床医学"
      ]
    },
    {
      "id": "g_c8dbc884a07d",
      "groupCode": "312104",
      "displayCode": "04",
      "groupName": "北京中医药大学04",
      "school": "北京中医药大学",
      "province": "北京",
      "city": "朝阳区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 29,
      "plan25": 26,
      "score25": 608,
      "score24": 593,
      "score23": 622,
      "rank25": 27151,
      "rank24": 35657,
      "rank23": 17335,
      "groupMajorCount": 12,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格",
        "医学"
      ],
      "majorSummary": "生物食品环境、医学、经管复合组",
      "majorClasses": [
        "中药学类",
        "中医学类",
        "药学类",
        "生物工程类",
        "管理科学与工程类"
      ],
      "majors": [
        {
          "key": "m_312104_07",
          "code": "07",
          "name": "中药学(时珍国药正华班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中药学",
          "majorClass": "中药学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 616,
          "rank25": 21044,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(时珍国药正华班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_08",
          "code": "08",
          "name": "中医学(卓越5+3一体化)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 5,
          "score25": 628,
          "rank25": 13360,
          "tuition": 5800,
          "duration": "5",
          "risk": false,
          "remark": "(卓越5+3一体化)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_09",
          "code": "09",
          "name": "中医学(卓越中医儿科班5+3一体化)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 627,
          "rank25": 13916,
          "tuition": 5800,
          "duration": "5",
          "risk": false,
          "remark": "(卓越中医儿科班5+3一体化)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_10",
          "code": "10",
          "name": "中医学(任应秋数智中医班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 612,
          "rank25": 23948,
          "tuition": 5800,
          "duration": "5",
          "risk": false,
          "remark": "(任应秋数智中医班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_11",
          "code": "11",
          "name": "中医学(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中医学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 8,
          "score25": 609,
          "rank25": 26331,
          "tuition": 5800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_12",
          "code": "12",
          "name": "中医骨伤科学(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中医骨伤科学",
          "majorClass": "中医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 608,
          "rank25": 27151,
          "tuition": 5800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_13",
          "code": "13",
          "name": "中药学(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中药学",
          "majorClass": "中药学类",
          "discipline": "医学",
          "plan26": 3,
          "score25": 609,
          "rank25": 26331,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_14",
          "code": "14",
          "name": "中药制药(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "中药制药",
          "majorClass": "中药学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 608,
          "rank25": 27151,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_15",
          "code": "15",
          "name": "药学(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "药学",
          "majorClass": "药学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 608,
          "rank25": 27151,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_16",
          "code": "16",
          "name": "生物工程(交叉创新班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "生物工程",
          "majorClass": "生物工程类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 610,
          "rank25": 25516,
          "tuition": 5500,
          "duration": "4",
          "risk": true,
          "remark": "(交叉创新班)(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_17",
          "code": "17",
          "name": "药事管理(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)",
          "baseName": "药事管理",
          "majorClass": "药学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 611,
          "rank25": 24770,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业有色觉要求,具体请查阅院校招生章程)(以下专业在良乡校区学习)"
        },
        {
          "key": "m_312104_18",
          "code": "18",
          "name": "大数据管理与应用(成思危拔尖人才班)(以下专业在良乡校区学习)",
          "baseName": "大数据管理与应用",
          "majorClass": "管理科学与工程类",
          "discipline": "管理学",
          "plan26": 2,
          "score25": 608,
          "rank25": 27151,
          "tuition": 5000,
          "duration": "4",
          "risk": false,
          "remark": "(成思危拔尖人才班)(以下专业在良乡校区学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "中药学",
        "中医学",
        "中医学",
        "中医学",
        "中医学",
        "中医骨伤科学",
        "中药学",
        "中药制药",
        "药学",
        "生物工程",
        "药事管理"
      ]
    },
    {
      "id": "g_7eefdef8cdcc",
      "groupCode": "240103",
      "displayCode": "03",
      "groupName": "福州大学03",
      "school": "福州大学",
      "province": "福建",
      "city": "福州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 6,
      "plan25": 6,
      "score25": 600,
      "score24": 591,
      "score23": 608,
      "rank25": 33986,
      "rank24": 37358,
      "rank23": 26161,
      "groupMajorCount": 2,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师",
        "双学位"
      ],
      "majorSummary": "地理建筑、计算机复合组",
      "majorClasses": [
        "建筑类",
        "工商管理类"
      ],
      "majors": [
        {
          "key": "m_240103_05",
          "code": "05",
          "name": "建筑学(以下专业第一学年在福州市铜盘校区学习,第二学年起在福州市旗山校区学习)",
          "baseName": "建筑学",
          "majorClass": "建筑类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 600,
          "rank25": 33986,
          "tuition": 5460,
          "duration": "5",
          "risk": false,
          "remark": "(以下专业第一学年在福州市铜盘校区学习,第二学年起在福州市旗山校区学习)"
        },
        {
          "key": "m_240103_06",
          "code": "06",
          "name": "会计学(会计学+数据科学与大数据技术双学士学位)(以下专业第一学年在福州市铜盘校区学习,第二学年起在福州市旗山校区学习)",
          "baseName": "会计学",
          "majorClass": "工商管理类",
          "discipline": "管理学",
          "plan26": 3,
          "score25": 607,
          "rank25": 27966,
          "tuition": 5460,
          "duration": "4",
          "risk": false,
          "remark": "(会计学+数据科学与大数据技术双学士学位)(以下专业第一学年在福州市铜盘校区学习,第二学年起在福州市旗山校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_cbdd08a9dbf9",
      "groupCode": "430908",
      "displayCode": "08",
      "groupName": "哈尔滨医科大学08",
      "school": "哈尔滨医科大学",
      "province": "黑龙江",
      "city": "哈尔滨",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学和生物",
      "plan26": 19,
      "plan25": 18,
      "score25": 590,
      "score24": 607,
      "score23": 602,
      "rank25": 43571,
      "rank24": 24905,
      "rank23": 30377,
      "groupMajorCount": 8,
      "tags": [
        "保研资格",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "临床医学类",
        "口腔医学类"
      ],
      "majors": [
        {
          "key": "m_430908_16",
          "code": "16",
          "name": "临床医学(5+3一体化)(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 3,
          "score25": 619,
          "rank25": 19005,
          "tuition": 4800,
          "duration": "5",
          "risk": false,
          "remark": "(5+3一体化)(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_17",
          "code": "17",
          "name": "临床医学(5+3一体化)(儿科学)(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 608,
          "rank25": 27151,
          "tuition": 4800,
          "duration": "5",
          "risk": false,
          "remark": "(5+3一体化)(儿科学)(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_18",
          "code": "18",
          "name": "临床医学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 9,
          "score25": 596,
          "rank25": 37721,
          "tuition": 4800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_19",
          "code": "19",
          "name": "麻醉学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "麻醉学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 594,
          "rank25": 39621,
          "tuition": 4800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_20",
          "code": "20",
          "name": "医学影像学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "医学影像学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 590,
          "rank25": 43571,
          "tuition": 5000,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_21",
          "code": "21",
          "name": "儿科学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "儿科学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 591,
          "rank25": 42526,
          "tuition": 5000,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_22",
          "code": "22",
          "name": "口腔医学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "口腔医学",
          "majorClass": "口腔医学类",
          "discipline": "医学",
          "plan26": 2,
          "score25": 591,
          "rank25": 42526,
          "tuition": 4800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        },
        {
          "key": "m_430908_23",
          "code": "23",
          "name": "眼视光医学(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)",
          "baseName": "眼视光医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 591,
          "rank25": 42526,
          "tuition": 5000,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程。以下专业在校本部学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "临床医学",
        "临床医学",
        "临床医学",
        "麻醉学",
        "医学影像学",
        "儿科学",
        "口腔医学",
        "眼视光医学"
      ]
    },
    {
      "id": "g_2212ed15e6ed",
      "groupCode": "330703",
      "displayCode": "03",
      "groupName": "河北工业大学03",
      "school": "河北工业大学",
      "province": "天津",
      "city": "北辰区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 8,
      "plan25": 7,
      "score25": 600,
      "score24": 596,
      "score23": 604,
      "rank25": 33986,
      "rank24": 33188,
      "rank23": 28962,
      "groupMajorCount": 4,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师",
        "医学"
      ],
      "majorSummary": "生物食品环境、数学物理复合组",
      "majorClasses": [
        "物理学类",
        "生物工程类",
        "海洋科学类",
        "生物医学工程类"
      ],
      "majors": [
        {
          "key": "m_330703_05",
          "code": "05",
          "name": "应用物理学(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "应用物理学",
          "majorClass": "物理学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 604,
          "rank25": 30493,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_330703_06",
          "code": "06",
          "name": "生物工程(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "生物工程",
          "majorClass": "生物工程类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 601,
          "rank25": 33070,
          "tuition": 5300,
          "duration": "4",
          "risk": true,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_330703_07",
          "code": "07",
          "name": "海洋技术(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "海洋技术",
          "majorClass": "海洋科学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 600,
          "rank25": 33986,
          "tuition": 5300,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_330703_08",
          "code": "08",
          "name": "生物医学工程(报考该专业组有色觉要求,具体请查阅院校招生章程)",
          "baseName": "生物医学工程",
          "majorClass": "生物医学工程类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 601,
          "rank25": 33070,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "应用物理学",
        "生物工程",
        "海洋技术",
        "生物医学工程"
      ]
    },
    {
      "id": "g_a83ddb0a0076",
      "groupCode": "330704",
      "displayCode": "04",
      "groupName": "河北工业大学04",
      "school": "河北工业大学",
      "province": "天津",
      "city": "北辰区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 12,
      "plan25": 11,
      "score25": 598,
      "score24": 596,
      "score23": 605,
      "rank25": 35804,
      "rank24": 33188,
      "rank23": 28268,
      "groupMajorCount": 6,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "机械土木、自动化、艺术体育复合组",
      "majorClasses": [
        "机械类",
        "土木类",
        "工业工程类",
        "材料类"
      ],
      "majors": [
        {
          "key": "m_330704_09",
          "code": "09",
          "name": "车辆工程",
          "baseName": "车辆工程",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_330704_10",
          "code": "10",
          "name": "智能制造工程",
          "baseName": "智能制造工程",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_330704_11",
          "code": "11",
          "name": "建筑环境与能源应用工程",
          "baseName": "建筑环境与能源应用工程",
          "majorClass": "土木类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 598,
          "rank25": 35804,
          "tuition": 5800,
          "duration": "4",
          "risk": true,
          "remark": ""
        },
        {
          "key": "m_330704_12",
          "code": "12",
          "name": "工业工程",
          "baseName": "工业工程",
          "majorClass": "工业工程类",
          "discipline": "管理学",
          "plan26": 2,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5500,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_330704_13",
          "code": "13",
          "name": "工业设计",
          "baseName": "工业设计",
          "majorClass": "机械类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 613,
          "rank25": 23215,
          "tuition": 5800,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_330704_14",
          "code": "14",
          "name": "电子信息材料",
          "baseName": "电子信息材料",
          "majorClass": "材料类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 614,
          "rank25": 22496,
          "tuition": 5800,
          "duration": "4",
          "risk": true,
          "remark": ""
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "建筑环境与能源应用工程",
        "电子信息材料"
      ]
    },
    {
      "id": "g_cd05e97bb145",
      "groupCode": "110628",
      "displayCode": "28",
      "groupName": "南京信息工程大学28",
      "school": "南京信息工程大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 413,
      "plan25": 470,
      "score25": 596,
      "score24": 600,
      "score23": 604,
      "rank25": 37721,
      "rank24": 29983,
      "rank23": 28962,
      "groupMajorCount": 7,
      "tags": [
        "双一流",
        "国重点",
        "保研资格",
        "卓越工程师",
        "联合培养"
      ],
      "majorSummary": "计算机组",
      "majorClasses": [
        "计算机类"
      ],
      "majors": [
        {
          "key": "m_110628_70",
          "code": "70",
          "name": "软件工程(与杭州海康威视数字技术股份有限公司联合培养)",
          "baseName": "软件工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 15,
          "score25": 614,
          "rank25": 22496,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(与杭州海康威视数字技术股份有限公司联合培养)"
        },
        {
          "key": "m_110628_71",
          "code": "71",
          "name": "计算机科学与技术(省拔尖学生培养基地)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 15,
          "score25": 612,
          "rank25": 23948,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(省拔尖学生培养基地)"
        },
        {
          "key": "m_110628_72",
          "code": "72",
          "name": "计算机科学与技术(科教融合拔尖班)",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 28,
          "score25": 622,
          "rank25": 17029,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(科教融合拔尖班)"
        },
        {
          "key": "m_110628_73",
          "code": "73",
          "name": "软件工程(科教融合拔尖班)",
          "baseName": "软件工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 20,
          "score25": 609,
          "rank25": 26331,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(科教融合拔尖班)"
        },
        {
          "key": "m_110628_74",
          "code": "74",
          "name": "计算机科学与技术",
          "baseName": "计算机科学与技术",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 162,
          "score25": 607,
          "rank25": 27966,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110628_75",
          "code": "75",
          "name": "物联网工程",
          "baseName": "物联网工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 55,
          "score25": 596,
          "rank25": 37721,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": ""
        },
        {
          "key": "m_110628_76",
          "code": "76",
          "name": "软件工程",
          "baseName": "软件工程",
          "majorClass": "计算机类",
          "discipline": "工学",
          "plan26": 118,
          "score25": 606,
          "rank25": 28842,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": ""
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_5cb4acdfb41b",
      "groupCode": "111219",
      "displayCode": "19",
      "groupName": "南京医科大学19",
      "school": "南京医科大学",
      "province": "江苏",
      "city": "南京",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 636,
      "plan25": 554,
      "score25": 587,
      "score24": 606,
      "score23": 607,
      "rank25": 46627,
      "rank24": 25606,
      "rank23": 26858,
      "groupMajorCount": 7,
      "tags": [
        "双一流",
        "保研资格",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "临床医学类"
      ],
      "majors": [
        {
          "key": "m_111219_36",
          "code": "36",
          "name": "临床医学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 454,
          "score25": 598,
          "rank25": 35804,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_37",
          "code": "37",
          "name": "医学影像学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "医学影像学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 27,
          "score25": 595,
          "rank25": 38686,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_38",
          "code": "38",
          "name": "眼视光医学(数智创新班)(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "眼视光医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 40,
          "score25": null,
          "rank25": null,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(数智创新班)(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_39",
          "code": "39",
          "name": "眼视光医学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "眼视光医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 31,
          "score25": 594,
          "rank25": 39621,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_40",
          "code": "40",
          "name": "精神医学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "精神医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 36,
          "score25": 589,
          "rank25": 44619,
          "tuition": 6800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_41",
          "code": "41",
          "name": "放射医学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "放射医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 36,
          "score25": 587,
          "rank25": 46627,
          "tuition": 6800,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        },
        {
          "key": "m_111219_42",
          "code": "42",
          "name": "儿科学(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)",
          "baseName": "儿科学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 12,
          "score25": 594,
          "rank25": 39621,
          "tuition": 7480,
          "duration": "5",
          "risk": false,
          "remark": "(报考该专业组有色觉要求,具体请查阅院校招生章程)(江宁校区)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "临床医学",
        "医学影像学",
        "眼视光医学",
        "眼视光医学",
        "精神医学",
        "放射医学",
        "儿科学"
      ]
    },
    {
      "id": "g_1b919c96502d",
      "groupCode": "730102",
      "displayCode": "02",
      "groupName": "青海大学02",
      "school": "青海大学",
      "province": "青海",
      "city": "西宁",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学和生物",
      "plan26": 1,
      "plan25": 1,
      "score25": 598,
      "score24": 595,
      "score23": 606,
      "rank25": 35804,
      "rank24": 33981,
      "rank23": 27545,
      "groupMajorCount": 1,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师",
        "医学"
      ],
      "majorSummary": "医学组",
      "majorClasses": [
        "临床医学类"
      ],
      "majors": [
        {
          "key": "m_730102_08",
          "code": "08",
          "name": "临床医学",
          "baseName": "临床医学",
          "majorClass": "临床医学类",
          "discipline": "医学",
          "plan26": 1,
          "score25": 598,
          "rank25": 35804,
          "tuition": 5770,
          "duration": "5",
          "risk": false,
          "remark": ""
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_6da92e34f4e2",
      "groupCode": "126152",
      "displayCode": "52",
      "groupName": "苏州大学52",
      "school": "苏州大学",
      "province": "江苏",
      "city": "苏州",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 108,
      "plan25": 112,
      "score25": 604,
      "score24": 598,
      "score23": 597,
      "rank25": 30493,
      "rank24": 31528,
      "rank23": 34107,
      "groupMajorCount": 4,
      "tags": [
        "211",
        "双一流",
        "保研资格",
        "卓越工程师"
      ],
      "majorSummary": "化学材料、艺术体育复合组",
      "majorClasses": [
        "轻工类",
        "纺织类"
      ],
      "majors": [
        {
          "key": "m_126152_C1",
          "code": "C1",
          "name": "轻化工程(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "轻化工程",
          "majorClass": "轻工类",
          "discipline": "工学",
          "plan26": 27,
          "score25": 606,
          "rank25": 28842,
          "tuition": 6380,
          "duration": "4",
          "risk": true,
          "remark": "(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_126152_C2",
          "code": "C2",
          "name": "纺织工程(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "纺织工程",
          "majorClass": "纺织类",
          "discipline": "工学",
          "plan26": 35,
          "score25": 605,
          "rank25": 29639,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_126152_C3",
          "code": "C3",
          "name": "服装设计与工程(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "服装设计与工程",
          "majorClass": "纺织类",
          "discipline": "工学",
          "plan26": 25,
          "score25": 604,
          "rank25": 30493,
          "tuition": 6380,
          "duration": "4",
          "risk": false,
          "remark": "(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)"
        },
        {
          "key": "m_126152_C4",
          "code": "C4",
          "name": "非织造材料与工程(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)",
          "baseName": "非织造材料与工程",
          "majorClass": "纺织类",
          "discipline": "工学",
          "plan26": 21,
          "score25": 604,
          "rank25": 30493,
          "tuition": 6380,
          "duration": "4",
          "risk": true,
          "remark": "(报考该专业组部分专业有色觉要求,具体请查阅院校招生章程)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "轻化工程",
        "纺织工程",
        "服装设计与工程",
        "非织造材料与工程"
      ]
    },
    {
      "id": "g_7e318f546804",
      "groupCode": "710106",
      "displayCode": "06",
      "groupName": "西北大学06",
      "school": "西北大学",
      "province": "陕西",
      "city": "西安",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 25,
      "plan25": 29,
      "score25": 603,
      "score24": 598,
      "score23": 598,
      "rank25": 31363,
      "rank24": 31528,
      "rank23": 33367,
      "groupMajorCount": 10,
      "tags": [
        "211",
        "双一流",
        "保研资格"
      ],
      "majorSummary": "化学材料、生物食品环境、电子信息复合组",
      "majorClasses": [
        "数学类",
        "化学类",
        "物理学类",
        "地质学类",
        "生物科学类",
        "电子信息类",
        "化工与制药类",
        "生物工程类",
        "食品科学与工程类"
      ],
      "majors": [
        {
          "key": "m_710106_13",
          "code": "13",
          "name": "信息与计算科学(网络安全实验班)(以下专业除注明外在长安校区学习)",
          "baseName": "信息与计算科学",
          "majorClass": "数学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 607,
          "rank25": 27966,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(网络安全实验班)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_14",
          "code": "14",
          "name": "化学(国家拔尖学生培养基地)(以下专业除注明外在长安校区学习)",
          "baseName": "化学",
          "majorClass": "化学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 607,
          "rank25": 27966,
          "tuition": 5250,
          "duration": "4",
          "risk": false,
          "remark": "(国家拔尖学生培养基地)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_15",
          "code": "15",
          "name": "化学类(应用化学、化学生物学、材料化学)(以下专业除注明外在长安校区学习)",
          "baseName": "化学类",
          "majorClass": "化学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 604,
          "rank25": 30493,
          "tuition": 6600,
          "duration": "4",
          "risk": true,
          "remark": "(应用化学、化学生物学、材料化学)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_16",
          "code": "16",
          "name": "应用物理学(智能光电创新实验班)(以下专业除注明外在长安校区学习)",
          "baseName": "应用物理学",
          "majorClass": "物理学类",
          "discipline": "理学",
          "plan26": 4,
          "score25": 609,
          "rank25": 26331,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(智能光电创新实验班)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_17",
          "code": "17",
          "name": "地质学(基地班)(以下专业除注明外在长安校区学习)",
          "baseName": "地质学",
          "majorClass": "地质学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 607,
          "rank25": 27966,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(基地班)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_18",
          "code": "18",
          "name": "生物科学(太白校区)(基地班)(以下专业除注明外在长安校区学习)",
          "baseName": "生物科学",
          "majorClass": "生物科学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 608,
          "rank25": 27151,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(太白校区)(基地班)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_19",
          "code": "19",
          "name": "电子信息类(通信工程、电子信息工程、电子科学与技术)(以下专业除注明外在长安校区学习)",
          "baseName": "电子信息类",
          "majorClass": "电子信息类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 609,
          "rank25": 26331,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(通信工程、电子信息工程、电子科学与技术)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_20",
          "code": "20",
          "name": "化工与制药类(化学工程与工艺、制药工程、能源化学工程)(以下专业除注明外在长安校区学习)",
          "baseName": "化工与制药类",
          "majorClass": "化工与制药类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 603,
          "rank25": 31363,
          "tuition": 6600,
          "duration": "4",
          "risk": true,
          "remark": "(化学工程与工艺、制药工程、能源化学工程)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_21",
          "code": "21",
          "name": "生物工程(生物智造创新实验班)(以下专业除注明外在长安校区学习)",
          "baseName": "生物工程",
          "majorClass": "生物工程类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 603,
          "rank25": 31363,
          "tuition": 6600,
          "duration": "4",
          "risk": true,
          "remark": "(生物智造创新实验班)(以下专业除注明外在长安校区学习)"
        },
        {
          "key": "m_710106_22",
          "code": "22",
          "name": "食品科学与工程(太白校区)(以下专业除注明外在长安校区学习)",
          "baseName": "食品科学与工程",
          "majorClass": "食品科学与工程类",
          "discipline": "工学",
          "plan26": 3,
          "score25": 606,
          "rank25": 28842,
          "tuition": 6600,
          "duration": "4",
          "risk": false,
          "remark": "(太白校区)(以下专业除注明外在长安校区学习)"
        }
      ],
      "medicalWarning": true,
      "warningMajorNames": [
        "化学类",
        "化工与制药类",
        "生物工程"
      ]
    },
    {
      "id": "g_a3951f51a40d",
      "groupCode": "530704",
      "displayCode": "04",
      "groupName": "长沙理工大学04",
      "school": "长沙理工大学",
      "province": "湖南",
      "city": "长沙",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "化学",
      "plan26": 2,
      "plan25": 2,
      "score25": 601,
      "score24": 600,
      "score23": 598,
      "rank25": 33070,
      "rank24": 29983,
      "rank23": 33367,
      "groupMajorCount": 1,
      "tags": [
        "保研资格",
        "卓越工程师",
        "中外合作",
        "高收费"
      ],
      "majorSummary": "中外合作：电气工程及其自动化",
      "majorClasses": [
        "电气类"
      ],
      "majors": [
        {
          "key": "m_530704_07",
          "code": "07",
          "name": "电气工程及其自动化(中外合作办学)",
          "baseName": "电气工程及其自动化",
          "majorClass": "电气类",
          "discipline": "工学",
          "plan26": 2,
          "score25": 601,
          "rank25": 33070,
          "tuition": 30000,
          "duration": "4",
          "risk": false,
          "remark": "(中外合作办学)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_fd89b33d0180",
      "groupCode": "220605",
      "displayCode": "05",
      "groupName": "浙江师范大学05",
      "school": "浙江师范大学",
      "province": "浙江",
      "city": "金华",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "不限",
      "plan26": 4,
      "plan25": 4,
      "score25": 592,
      "score24": 601,
      "score23": 606,
      "rank25": 41600,
      "rank24": 29207,
      "rank23": 27545,
      "groupMajorCount": 2,
      "tags": [
        "保研资格",
        "师范"
      ],
      "majorSummary": "教育心理、文史语言新闻复合组",
      "majorClasses": [
        "心理学类",
        "中国语言文学类"
      ],
      "majors": [
        {
          "key": "m_220605_06",
          "code": "06",
          "name": "应用心理学(师范)(金华校区)",
          "baseName": "应用心理学",
          "majorClass": "心理学类",
          "discipline": "理学",
          "plan26": 2,
          "score25": 592,
          "rank25": 41600,
          "tuition": 5300,
          "duration": "4",
          "risk": false,
          "remark": "(师范)(金华校区)"
        },
        {
          "key": "m_220605_07",
          "code": "07",
          "name": "汉语言文学(师范)(金华校区)",
          "baseName": "汉语言文学",
          "majorClass": "中国语言文学类",
          "discipline": "文学",
          "plan26": 2,
          "score25": 595,
          "rank25": 38686,
          "tuition": 6095,
          "duration": "4",
          "risk": false,
          "remark": "(师范)(金华校区)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    },
    {
      "id": "g_6fd4cc33cf47",
      "groupCode": "311413",
      "displayCode": "13",
      "groupName": "北京林业大学13",
      "school": "北京林业大学",
      "province": "北京",
      "city": "海淀区",
      "subject": "物理",
      "batch": "本科批",
      "requirement": "生物",
      "plan26": 2,
      "plan25": 2,
      "score25": 600,
      "score24": 598,
      "score23": 603,
      "rank25": 33986,
      "rank24": 31528,
      "rank23": 29716,
      "groupMajorCount": 1,
      "tags": [
        "211",
        "双一流",
        "国重点",
        "保研资格"
      ],
      "majorSummary": "园林",
      "majorClasses": [
        "林学类"
      ],
      "majors": [
        {
          "key": "m_311413_54",
          "code": "54",
          "name": "园林(以下专业第一、二学年在北京校区学习,第三学年起在雄安校区学习)",
          "baseName": "园林",
          "majorClass": "林学类",
          "discipline": "农学",
          "plan26": 2,
          "score25": 600,
          "rank25": 33986,
          "tuition": 5000,
          "duration": "4",
          "risk": false,
          "remark": "(以下专业第一、二学年在北京校区学习,第三学年起在雄安校区学习)"
        }
      ],
      "medicalWarning": false,
      "warningMajorNames": []
    }
  ]
};
